project:
  type: book
  output-dir: docs

book:
  title: "Análisis de Sobrevivencia"
  author: "Luis A. Barboza"
  date: "3/13/2023"
  chapters:
    - index.qmd
    - Preliminares.qmd
    - estNP.qmd
    - PH.qmd
    - RSP.qmd
    - DRSP.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

