<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Análisis de Sobrevivencia - 4&nbsp; Regresión Semiparamétrica con Riesgos Proporcionales</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./DRSP.html" rel="next">
<link href="./PH.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Regresión Semiparamétrica con Riesgos Proporcionales</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Análisis de Sobrevivencia</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Introducción</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Preliminares.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Preliminares</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./estNP.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Estimación No-Paramétrica</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./PH.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Pruebas de Hipótesis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./RSP.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Regresión Semiparamétrica con Riesgos Proporcionales</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DRSP.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Análisis de Diagnósticos en el Modelo de Cox</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">Referencias</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción"><span class="toc-section-number">4.1</span>  Introducción</a></li>
  <li><a href="#verosimilitud-parcial" id="toc-verosimilitud-parcial" class="nav-link" data-scroll-target="#verosimilitud-parcial"><span class="toc-section-number">4.2</span>  Verosimilitud Parcial</a>
  <ul class="collapse">
  <li><a href="#pruebas-de-hipótesis-para-beta" id="toc-pruebas-de-hipótesis-para-beta" class="nav-link" data-scroll-target="#pruebas-de-hipótesis-para-beta"><span class="toc-section-number">4.2.1</span>  3 pruebas de hipótesis para <span class="math inline">\(\beta\)</span></a></li>
  <li><a href="#verosimilitud-parcial-cuando-hay-repeticiones" id="toc-verosimilitud-parcial-cuando-hay-repeticiones" class="nav-link" data-scroll-target="#verosimilitud-parcial-cuando-hay-repeticiones"><span class="toc-section-number">4.2.2</span>  Verosimilitud parcial cuando hay repeticiones</a></li>
  </ul></li>
  <li><a href="#pruebas-locales" id="toc-pruebas-locales" class="nav-link" data-scroll-target="#pruebas-locales"><span class="toc-section-number">4.3</span>  Pruebas Locales</a></li>
  <li><a href="#discretización-de-una-variable-continua" id="toc-discretización-de-una-variable-continua" class="nav-link" data-scroll-target="#discretización-de-una-variable-continua"><span class="toc-section-number">4.4</span>  Discretización de una variable continua</a></li>
  <li><a href="#estimación-de-la-función-de-sobrevivencia" id="toc-estimación-de-la-función-de-sobrevivencia" class="nav-link" data-scroll-target="#estimación-de-la-función-de-sobrevivencia"><span class="toc-section-number">4.5</span>  Estimación de la función de sobrevivencia</a></li>
  <li><a href="#covariables-dependientes-del-tiempo" id="toc-covariables-dependientes-del-tiempo" class="nav-link" data-scroll-target="#covariables-dependientes-del-tiempo"><span class="toc-section-number">4.6</span>  Covariables dependientes del tiempo</a>
  <ul class="collapse">
  <li><a href="#aplicación-prueba-de-riesgos-proporcionales" id="toc-aplicación-prueba-de-riesgos-proporcionales" class="nav-link" data-scroll-target="#aplicación-prueba-de-riesgos-proporcionales"><span class="toc-section-number">4.6.1</span>  Aplicación: Prueba de Riesgos Proporcionales</a></li>
  </ul></li>
  <li><a href="#modelos-de-riesgos-proporcionales-estratificados" id="toc-modelos-de-riesgos-proporcionales-estratificados" class="nav-link" data-scroll-target="#modelos-de-riesgos-proporcionales-estratificados"><span class="toc-section-number">4.7</span>  Modelos de riesgos proporcionales estratificados</a></li>
  <li><a href="#truncamiento-por-la-izquierda" id="toc-truncamiento-por-la-izquierda" class="nav-link" data-scroll-target="#truncamiento-por-la-izquierda"><span class="toc-section-number">4.8</span>  Truncamiento por la izquierda</a></li>
  <li><a href="#laboratorio" id="toc-laboratorio" class="nav-link" data-scroll-target="#laboratorio"><span class="toc-section-number">4.9</span>  Laboratorio</a>
  <ul class="collapse">
  <li><a href="#primer-ejemplo-ejemplo-8.1" id="toc-primer-ejemplo-ejemplo-8.1" class="nav-link" data-scroll-target="#primer-ejemplo-ejemplo-8.1"><span class="toc-section-number">4.9.1</span>  Primer Ejemplo (Ejemplo 8.1)</a></li>
  <li><a href="#segundo-ejemplo-ejemplo-8.2" id="toc-segundo-ejemplo-ejemplo-8.2" class="nav-link" data-scroll-target="#segundo-ejemplo-ejemplo-8.2"><span class="toc-section-number">4.9.2</span>  Segundo ejemplo (Ejemplo 8.2)</a></li>
  <li><a href="#tercer-ejemplo-ejemplo-8.3" id="toc-tercer-ejemplo-ejemplo-8.3" class="nav-link" data-scroll-target="#tercer-ejemplo-ejemplo-8.3"><span class="toc-section-number">4.9.3</span>  Tercer ejemplo (Ejemplo 8.3)</a></li>
  <li><a href="#selección-de-variables" id="toc-selección-de-variables" class="nav-link" data-scroll-target="#selección-de-variables"><span class="toc-section-number">4.9.4</span>  Selección de variables</a></li>
  <li><a href="#covariables-dependientes-del-tiempo-1" id="toc-covariables-dependientes-del-tiempo-1" class="nav-link" data-scroll-target="#covariables-dependientes-del-tiempo-1"><span class="toc-section-number">4.9.5</span>  Covariables dependientes del tiempo</a></li>
  <li><a href="#prueba-alternativa-de-riesgos-proporcionales" id="toc-prueba-alternativa-de-riesgos-proporcionales" class="nav-link" data-scroll-target="#prueba-alternativa-de-riesgos-proporcionales"><span class="toc-section-number">4.9.6</span>  Prueba alternativa de riesgos proporcionales:</a></li>
  <li><a href="#datos-truncados-por-la-izquierda" id="toc-datos-truncados-por-la-izquierda" class="nav-link" data-scroll-target="#datos-truncados-por-la-izquierda"><span class="toc-section-number">4.9.7</span>  Datos truncados por la izquierda</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="RSP" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Regresión Semiparamétrica con Riesgos Proporcionales</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="introducción" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="introducción"><span class="header-section-number">4.1</span> Introducción</h2>
<p><em>Objetivo</em>: Modelar la probabilidad de sobrevivencia o tasa de riesgo bajo la presencia de información adicional en la forma de covariables.</p>
<p>Utilizamos la misma notación de los capítulos anteriores en donde <span class="math inline">\(X\)</span>: tiempo aleatorio hasta la ocurrencia de un riesgo de interés. Los datos consisten en tripletas <span class="math inline">\((T_j,\delta_j,Z_j(t))\)</span> para <span class="math inline">\(j=1,\ldots,n\)</span> donde</p>
<ul>
<li><span class="math inline">\(T_j\)</span>: tiempo de evento o censura para el paciente <span class="math inline">\(j\)</span>-ésimo.</li>
<li><span class="math inline">\(\delta_j\)</span>: indicador del evento.</li>
<li><span class="math inline">\(Z_j(t)=(Z_{j1}(t),\ldots,Z_{jp}(t))^T\)</span>: vector de <span class="math inline">\(p\)</span> covariables para el individuo <span class="math inline">\(j\)</span>-ésimo en tiempo <span class="math inline">\(t\)</span>.</li>
</ul>
<p><strong>Nota</strong>: por ahora asumiremos que <span class="math inline">\(Z_{jp}(t)\)</span> es constante con respecto al tiempo <span class="math inline">\(t\)</span>. (<span class="math inline">\(j=1,\dots,n\)</span> y <span class="math inline">\(k=1,\ldots,p\)</span>), es decir:</p>
<p><span class="math display">\[Z_j(t)=Z_j=(Z_{j1},\ldots,Z_{jp})^T\]</span></p>
<p>Sea <span class="math inline">\(h(t|Z)\)</span> la tasa de riesgo en tiempo <span class="math inline">\(t\)</span> para un individuo con covariables <span class="math inline">\(Z\)</span>. El modelo de Cox está dado por:</p>
<p><span class="math display">\[h(t|Z)=h_0(t)c(\beta^TZ)\]</span></p>
<p>donde <span class="math inline">\(h_0(t)\)</span> es la tasa de riesgo base (arbitraria), <span class="math inline">\(\beta=(\beta_1,\ldots,\beta_p)^T\)</span> y <span class="math inline">\(c(\cdot)\)</span> es una función conocida. Como <span class="math inline">\(h(t|Z)\)</span> debe ser positiva, una posible forma (y la más usual) de escoger <span class="math inline">\(c(\cdot)\)</span> es:</p>
<p><span class="math display">\[c(\beta^TZ)=\exp[\beta^TZ]=e^{\sum_{k=1}^p\beta_kZ_k}\]</span></p>
<p>lo que permite obtener el siguiente modelo lineal generalizado:</p>
<p><span class="math display">\[\log\left[\frac{h(t|Z)}{h_0(t)}\right]=\sum_{k=1}^p \beta_kZ_k\]</span> <strong>Nota</strong>: el tratamiento de las covariables tanto cuantitativas como categóricas es el mismo que el que se trabaja con modelos lineales.</p>
<p>Al modelo de Cox se le llama usualmente el <em>modelo de riesgos proporcionales</em> dado que si dos individuos tienen covariables <span class="math inline">\(Z\)</span> y <span class="math inline">\(Z^*\)</span>:</p>
<p><span class="math display">\[\frac{h(t|Z)}{h(t|Z^*)}=\frac{h_0(t)\exp\left[\sum_{k=1}^p\beta_kZ_k\right]}{h_0(t)\exp\left[\sum_{k=1}^p\beta_kZ_k^*\right]}=\exp\left[\sum_{k=1}^p\beta_k(Z_k-Z_k^*)\right]\]</span> es decir: <span class="math inline">\(h(t|Z)\propto h(t|Z^*)\)</span>. Al cociente <span class="math inline">\(\frac{h(t|Z)}{h(t|Z^*)}\)</span> se le llama riesgo relativo.</p>
<p>Por ejemplo, si <span class="math inline">\(Z_1\)</span>: variable tratamiento, es decir:</p>
<p><span class="math display">\[Z_1=\begin{cases}
1 &amp; \text{tratamiento} (Z)\\
0 &amp; \text{placebo} (Z^*)
\end{cases}
\]</span> y se asume que el resto de las covariables son iguales entre los dos individuos, entonces el riesgo relativo es:</p>
<p><span class="math display">\[\frac{h(t|Z)}{h(t|Z^*)}=\exp[\beta_1(1-0)+0]=e^{\beta_1}\]</span> <em>Nota</em>: la codificación de la variable tratamiento cambia la interpretación de <span class="math inline">\(\beta_1\)</span> ya que si:</p>
<p><span class="math display">\[Z_1=\begin{cases}
1 &amp; \text{placebo} (Z)\\
0 &amp; \text{tratamiento} (Z^*)
\end{cases}
\]</span> entonces el riesgo relativo sería <span class="math inline">\(e^{-\beta_1}\)</span>.</p>
<p>A las variables categóricas se le llaman en este contexto de análisis de sobrevivencia: <em>grupos de riesgo</em>. Si el grupo de riesgo está compuesto de tres niveles se puede usar dos covariables como indicadoras, por ejemplo si el grupo de riesgo es etnia con niveles: afroamericano, caucásico e hispánico; se puede definir: <span class="math inline">\(Z_1=1_{\text{Afroamericano}}\)</span>, <span class="math inline">\(Z_2=1_{\text{caucasico}}\)</span>, entonces:</p>
<span class="math display">\[\begin{align*}
    h(t|\text{Afroamericano})&amp;=h(t|Z_1=1,Z_2=0)=h_0(t)\exp[\beta_1]\\
    h(t|\text{Caucasico})&amp;=h(t|Z_1=0,Z_2=1)=h_0(t)\exp[\beta_2]\\
    h(t|\text{Hispanico})&amp;=h(t|Z_1=0,Z_2=0)=h_0(t)
\end{align*}\]</span>
<p>Si las variables son cuantitativas entonces la interpretación de los riesgos relativos se realiza al comparar cambios producto de un aumento en una unidad en la variable de análisis:</p>
<p><span class="math display">\[\frac{h(t|\text{Edad}+1)}{h(t|\text{Edad})}=e^{\beta_{\text{edad}}}\]</span> Otro aspecto importante es que la presencia de interacciones entre covariables afecta la interpretación, tal y como se observa en modelos más sencillos como regresión múltiple o logística. (ver final de la sección 8.2 del Klein.)</p>
</section>
<section id="verosimilitud-parcial" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="verosimilitud-parcial"><span class="header-section-number">4.2</span> Verosimilitud Parcial</h2>
<p>A nivel de datos, considere las tripletas de la sección anterior, no dependientes del tiempo: <span class="math inline">\((T_j,\delta_j,Z_j)\)</span>, para <span class="math inline">\(j=1,\ldots,n\)</span>.</p>
<p>Supuestos:</p>
<ul>
<li>No hay tiempos de ocurrencia del evento repetidos.</li>
<li>Dado <span class="math inline">\(Z_j\)</span>, los tiempos de ocurrencia y censura son independientes.</li>
</ul>
<p>Sea <span class="math inline">\(t_1&lt;t_2&lt;\cdots &lt;t_D\)</span> los tiempos de ocurrencia del evento y</p>
<ul>
<li><span class="math inline">\(Z_{(i)k}\)</span>: <span class="math inline">\(k\)</span>-ésima covariable del individuo cuyo tiempo de ocurrencia es <span class="math inline">\(t_i\)</span>.</li>
<li><span class="math inline">\(R(t_i)\)</span>: individuos en riesgo al tiempo <span class="math inline">\(t_i\)</span>.</li>
</ul>
<p><em>Inconveniente</em>: <span class="math inline">\(h_0(t)\)</span> debe ser estimado junto con los <span class="math inline">\(\beta\)</span>’s.</p>
<p><em>Solución</em>: calculamos la probabilidad de que un individuo le ocurra el riesgo en tiempo <span class="math inline">\(t_i\)</span> con covariables <span class="math inline">\(Z_{(i)}\)</span> dado que uno de los individuos en <span class="math inline">\(R(t_i)\)</span> le ocurrió el riesgo en tiempo <span class="math inline">\(t_i\)</span>:</p>
<span class="math display">\[\begin{align*}
    &amp;P[\text{individuo muere en $t_i$}|\text{una muerte en $t_i$}]\\
    &amp;=\frac{P[\text{individuo muere en $t_i$}|\text{sobrevive a $t_i$}]}{P[\text{una muerte en $t_i$}|\text{sobrevive a $t_i$}]}\\
    &amp;=\frac{\frac{f(t_i|Z_{(i)})}{S(t_i|Z_{(i)})}}{\sum_{j\in R(t_i)}\frac{f(t_i|Z_j)}{S(t_i|Z_j)}}=\frac{h(t_i|Z_{(i)})}{\sum_{j \in R(t_i)} h(t_i|Z_j)}=\frac{h_0(t_i)\exp(\beta^TZ_{(i)})}{h_0(t_i)\sum_{j \in R(t_i)} \exp(\beta^TZ_j)}\\
    &amp;=\frac{\exp(\beta^TZ_{(i)})}{\sum_{j \in R(t_i)} \exp(\beta^TZ_j)}
\end{align*}\]</span>
<p>La verosimilitud parcial se obtiene al multiplicar todas las probabilidades condicionales anteriores sobre todos los tiempos en donde ocurre el evento en la muestra:</p>
<p><span class="math display">\[L(\beta)=\prod_{i=1}^D\frac{\exp(\beta^TZ_{(i)})}{\sum_{j \in R(t_i)} \exp(\beta^TZ_j)}\]</span> El proceso de inferencia se realiza con <span class="math inline">\(L(\beta)\)</span> (no depende de <span class="math inline">\(h_0(t)\)</span>) o bien sobre la log-verosimilitud parcial:</p>
<p><span class="math display">\[LL(\beta)=\log L(\beta)=\sum_{i=1}^D\sum_{k=1}^p \beta_kZ_{(i)k}-\sum_{i=1}^D\log\left[\sum_{j \in R(t_i)}\sum_{k=1}^p\beta_kZ_{jk}\right]\]</span></p>
<p>definiendo funciones score:</p>
<p><span class="math display">\[U_h(\beta)=\frac{\partial }{\partial \beta_h}LL(\beta)\qquad h=1,\ldots,p\]</span></p>
<p>y resolviendo el sistema de <span class="math inline">\(p\)</span> ecuaciones no lineales:</p>
<p><span class="math display">\[U_h(\beta)=0\qquad h=1,\ldots,p\]</span> la solución es el estimador de máxima verosimilitud parcial de <span class="math inline">\(\beta\)</span>.</p>
<p>Como justificación al uso de la verosimilitud parcial como herramienta inferencial, asuma las tripletas <span class="math inline">\((T_j,\delta_j,Z_j)\)</span> como datos y escribamos la verosimilitud total de los parámetros <span class="math inline">\((\beta,h_0(t))\)</span>:</p>
<span class="math display">\[\begin{align*}
    L(\beta,h_0(t))&amp;=\prod_{j=1}^n f(T_j|Z_j)^{\delta_j}S(T_j|Z_j)^{1-\delta_j}\\
    &amp;=\prod_{j=1}^n h(T_j|Z_j)^{\delta_j}S(T_j|Z_j)\\
    &amp;=\prod_{j=1}^n h_0(T_j)^{\delta_j}[\exp(\beta^TZ_j)]^{\delta_j}\exp[-H_0(T_j)\exp(\beta^TZ_j)]\\
    &amp;=\left[\prod_{i=1}^D h_0(t_i)\exp(\beta^TZ_{(i)})\right]\cdot \exp\left[-\sum_{j=1}^n H_0(T_j)\exp(\beta^TZ_j)\right]
\end{align*}\]</span>
<p>Sea <span class="math inline">\(h_{0i}=h_0(t_i)\)</span>, <span class="math inline">\(i=1,\ldots,D\)</span> y <span class="math inline">\(H_0(T_j)=\sum_{t_i\leq T_j}h_{0i}\)</span> entonces:</p>
<p><span class="math display">\[L(\beta,h_0(t))=L_\beta(h_{01},\ldots,h_{0D})\propto \prod_{i=1}^Dh_{0i}\exp\left[-h_{0i}\sum_{j\in R(t_i)}\exp(\beta^TZ_j)\right]\]</span></p>
<p>y manteniendo <span class="math inline">\(\beta\)</span> fijo y maximizando con respecto a <span class="math inline">\(h_{0i}\)</span>:</p>
<p><span class="math display">\[\hat h_{0i}=\frac{1}{\sum_{j \in R(t_i)}\exp(\beta^TZ_j)}\]</span> es el estimador por máxima verosimilitud (de perfil) de <span class="math inline">\(h_{0i}\)</span>. A partir de esto definimos el <em>estimador de Breslow</em> de <span class="math inline">\(H_0(t)\)</span> como:</p>
<p><span class="math display">\[\hat H_0(t)=\sum_{t_i\leq t}\frac{1}{\sum_{j\in R(t_i)}\exp(\beta^TZ_j)}\]</span> y sustituyendo en la fórmula de verosimilitud completa:</p>
<p><span class="math display">\[L(\beta,\hat h_{0.})\propto \prod_{i=1}^D\frac{\exp[\beta^TZ_{(i)}]}{\sum_{j\in R(t_i)}\exp[\beta^TZ_j]}\]</span></p>
<section id="pruebas-de-hipótesis-para-beta" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="pruebas-de-hipótesis-para-beta"><span class="header-section-number">4.2.1</span> 3 pruebas de hipótesis para <span class="math inline">\(\beta\)</span></h3>
<p>Sea <span class="math inline">\(b=(b_1,\ldots,b_p)^T\)</span> el estimador por máxima verosimilitud parcial de <span class="math inline">\(\beta\)</span> y sea <span class="math inline">\(I(\beta)\)</span> la matriz de información <span class="math inline">\(p\times p\)</span> con entradas:</p>
<p><span class="math display">\[I_{gh}(\beta)=-\frac{\partial^2LL}{\partial\beta_g\partial\beta_h}(\beta)\]</span></p>
<ol type="1">
<li>Prueba de Wald</li>
</ol>
<p>Se sabe que <span class="math inline">\(b\sim N_p(\beta,I^{-1}(b))\)</span>. Entonces el estadístico de prueba con hipótesis nula: <span class="math inline">\(H_0: \beta=\beta_0\)</span> es:</p>
<p><span class="math display">\[X^2_w=(b-\beta_0)^TI(b)(b-\beta_0)\underset{H_0}{\sim}\chi^2_p\]</span></p>
<ol start="2" type="1">
<li>Prueba de cociente de verosimilitud.</li>
</ol>
<p>Bajo <span class="math inline">\(H_0: \beta=\beta_0\)</span>:</p>
<p><span class="math display">\[X^2_{LR}=2[LL(b)-LL(\beta_0)]\underset{H_0}{\sim}\chi^2_p\]</span></p>
<ol start="3" type="1">
<li>Prueba Score (o prueba de log-rank si no hay repeticiones)</li>
</ol>
<p>Sea <span class="math inline">\(U(\beta)=(U_1(\beta),\ldots,U_p(\beta))^T\)</span>. Entonces:</p>
<p><span class="math display">\[U(\beta)\overset{H_0}{\underset{\text{n grande}}{\sim}}N_p(0,I(\beta))\]</span> Entonces un estadístico de prueba de <span class="math inline">\(H_0: \beta=\beta_0\)</span> es:</p>
<p><span class="math display">\[X^2_{SC}=U(\beta_0)^TI^{-1}(\beta_0)U(\beta_0)\overset{H_0}{\underset{\text{n grande}}{\sim}}\chi_p^2\]</span></p>
</section>
<section id="verosimilitud-parcial-cuando-hay-repeticiones" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="verosimilitud-parcial-cuando-hay-repeticiones"><span class="header-section-number">4.2.2</span> Verosimilitud parcial cuando hay repeticiones</h3>
<p>Sea <span class="math inline">\(t_1&lt;t_2&lt;\cdots &lt;t_D\)</span> sean <span class="math inline">\(D\)</span> tiempos distintos de ocurrencia del evento, <span class="math inline">\(d_i\)</span>: número de eventos ocurridos en <span class="math inline">\(t_i\)</span> y <span class="math inline">\(\mathbb D_i\)</span>: conjunto de individuos que les ocurre el evento en <span class="math inline">\(t_i\)</span>. Sea</p>
<p><span class="math display">\[S_i=\sum_{j\in \mathbb D_i}Z_j\]</span> Las siguientes son formas distintas de construir la verosimilitud parcial cuando hay repeticiones en los tiempos de ocurrencia del riesgo:</p>
<ul>
<li>Verosimilitud parcial de Breslow (1974)</li>
</ul>
<p><span class="math display">\[L_1(\beta)=\prod_{i=1}^D\frac{\exp(\beta^TS_i)}{\left[\sum_{j \in R_i}\exp(\beta^TZ_j)\right]^{d_i}}\]</span></p>
<ul>
<li>Verosimilitud parcial de Efron (1977)</li>
</ul>
<p><span class="math display">\[L_2(\beta)=\prod_{i=1}^D\frac{\exp(\beta^TS_i)}{\prod_{j=1}^{d_i}\left[\sum_{k\in R_i}\exp(\beta^TZ_k)-\frac{j-1}{d_i}\sum_{k\in \mathbb D_i}\exp(\beta^TZ_k)\right]}\]</span></p>
<ul>
<li>Verosimilitud parcial de Cox (1972)</li>
</ul>
<p>Sea <span class="math inline">\(Q_i\)</span>: conjunto de todos los subconjuntos de <span class="math inline">\(d_i\)</span> individuos seleccionados de <span class="math inline">\(R_i\)</span>. Sea <span class="math inline">\(q=(q_1,\ldots,q_{d_i})\)</span> un elemento de <span class="math inline">\(Q_i\)</span> y defina <span class="math inline">\(s^*_q=\sum_{j=1}^{d_i}Z_{q_j}\)</span>, entonces:</p>
<p><span class="math display">\[L_3(\beta)=\prod_{i=1}^D\frac{\exp(\beta^TS_i)}{\sum_{q\in Q_i}\exp(\beta^Ts^*_q)}\]</span></p>
</section>
</section>
<section id="pruebas-locales" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="pruebas-locales"><span class="header-section-number">4.3</span> Pruebas Locales</h2>
<p>En este caso la hipótesis nula de interés es:</p>
<p><span class="math display">\[H_0: \beta_1=\beta_{10}\qquad \text{donde} \; \beta=(\beta_1^T,\beta_2^T)^T\]</span></p>
<p>y <span class="math inline">\(\beta_1\)</span> es un vector <span class="math inline">\(q\times 1\)</span> y <span class="math inline">\(\beta_2\)</span> es <span class="math inline">\((p-q)\times 1\)</span>.</p>
<ul>
<li>Prueba de Wald</li>
</ul>
<p>Sea <span class="math inline">\(b=(b_1^T,b_2^T)^T\)</span> los estimadores de máxima verosimilitud parcial de <span class="math inline">\(\beta\)</span>. Supongamos que particionamos la matriz de información <span class="math inline">\(I\)</span> como:</p>
<span class="math display">\[\begin{align*}
I=
   \begin{pmatrix}
     I_{11} &amp; I_{12} \\
     I_{21} &amp; I_{22}
   \end{pmatrix}
\end{align*}\]</span>
<p>donde <span class="math inline">\(I_{11}:q\times q\)</span> y <span class="math inline">\(I_{22}: (p-q)\times (p-q)\)</span> son los bloques correspondientes a <span class="math inline">\(\beta_1\)</span> y <span class="math inline">\(\beta_2\)</span> respectivamente. El estadístico de prueba en este caso es:</p>
<p><span class="math display">\[X^2_w=(b_1-\beta_{10})^T[I''(b)]^{-1}(b_1-\beta_{10})\]</span></p>
<p>donde <span class="math inline">\(I''(b)\)</span> es la submatriz <span class="math inline">\(q\times q\)</span> (superior) de <span class="math inline">\(I^{-1}(b)\)</span> y:</p>
<p><span class="math display">\[X_w^2\overset{H_0}{\underset{\text{n grande}}{\sim}}\chi_q^2\]</span></p>
<p>Sea <span class="math inline">\(b_2(\beta_{10})\)</span> los estimadores de máxima verosimilitud parciales de <span class="math inline">\(\beta_2\)</span> basados en la log-verosimilitud parcial de <span class="math inline">\(\beta\)</span> fijando las primeras <span class="math inline">\(q\)</span> entradas con el valor <span class="math inline">\(\beta_{10}\)</span>.</p>
<ul>
<li>Prueba de cociente de verosimilitud</li>
</ul>
<p>El estadístico correspondiente sería:</p>
<p><span class="math display">\[X^2_{LR}=2\left(LL(b)-LL[\beta_{10},b_2(\beta_{10})]\right)\overset{H_0}{\underset{\text{n grande}}{\sim}}\chi_q^2\]</span></p>
<ul>
<li>Prueba Score:</li>
</ul>
<p>Sea <span class="math inline">\(U_1[\beta_{10},b_2(\beta_{10})]\)</span> el score con tamaño <span class="math inline">\(q\times 1\)</span> para <span class="math inline">\(\beta_1\)</span> evaluado en <span class="math inline">\((\beta_{10}^T,b_2(\beta_{10})^T)^T\)</span>. Entonces:</p>
<p><span class="math display">\[X^2_{SC}=U_1[\beta_{10},b_2(\beta_{10})]^T[I''(\beta_{10},b_2(\beta_{10}))]U_1[\beta_{10},b_2(\beta_{10})]\overset{H_0}{\underset{\text{n grande}}{\sim}}\chi_q^2\]</span></p>
<p>Algunas veces se quiere probar una hipótesis sobre un contraste de los parámetros a través de una prueba de Wald. Sea:</p>
<span class="math display">\[\begin{align*}
C=
   \begin{pmatrix}
   c_1^T\\
   c_2^T\\
   \vdots \\
   c_q^T
   \end{pmatrix}_{q\times p}
\end{align*}\]</span>
<p>donde <span class="math inline">\(q\leq p\)</span> y <span class="math inline">\(C\)</span> es de rango completo. Además <span class="math inline">\(c_k^T=(c_{k1},c_{k2},\ldots,c_{kp})\)</span> y se quiere probar la hipótesis:</p>
<p><span class="math display">\[H_0: C\beta=C\beta_0\]</span></p>
<p>a través del estadístico:</p>
<p><span class="math display">\[(Cb-C\beta_0)^T[CI^{-1}(b)C^T]^{-1}(Cb-C\beta_0)\overset{H_0}{\underset{\text{n grande}}{\sim}}\chi_q^2\]</span></p>
</section>
<section id="discretización-de-una-variable-continua" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="discretización-de-una-variable-continua"><span class="header-section-number">4.4</span> Discretización de una variable continua</h2>
<p>Con el fin de facilitar la interpretación de un riesgo relativo de una covariable cuantitativa, se puede convertir en una variable dicotómica. El principal problema de esta conversión es la pérdida de información, pero esta pérdida se puede minimizar usando razonamiento biológico a priori o bien que la decisión en la conversión sea basada en datos.</p>
<p>Como principal objetivo, si <span class="math inline">\(X\)</span> es una variable aleatoria continua, queremos definir <span class="math inline">\(Z=1_{X\geq c}\)</span> que cause una diferencia máxima entre los resultados de un estadístico calculado cuando <span class="math inline">\(Z=1\)</span> con respecto a <span class="math inline">\(Z=0\)</span> (máximo grado de separación de información entre los dos grupos).</p>
<p><strong>Contal y O’Quigley (1999)</strong></p>
<p>Considere un conjunto de cortes <span class="math inline">\(\{c_k\}\)</span> y para cada <span class="math inline">\(k\)</span> se calcula el estadístico log-rank sobre el grupo en donde <span class="math inline">\(X\leq c_k\)</span> menos el mismo estadístico sobre el grupo donde <span class="math inline">\(X\geq c_k\)</span>, es decir:</p>
<p><span class="math display">\[S_k=\sum_{i=1}^D\left[d_i^+-d_i\frac{r_i^+}{r_i}\right]\]</span></p>
<p>donde</p>
<ul>
<li><p><span class="math inline">\(d_i, r_i\)</span>: número total de eventos y grupo en riesgo.</p></li>
<li><p><span class="math inline">\(d_i^+, r_i^+\)</span>: número total de eventos y grupo en riesgo cuando <span class="math inline">\(X\geq c_k\)</span>.</p></li>
<li><p><span class="math inline">\(D\)</span>: número de tiempos de ocurrencia de eventos (distintos).</p></li>
</ul>
<p>El corte estimado <span class="math inline">\(\hat c=\text{argmax}_{c_k}|S_k|\)</span>. Bajo esta escogencia de <span class="math inline">\(\hat c\)</span>, el modelo de Cox es:</p>
<p><span class="math display">\[h(t|X)=h_0(t)\exp[bZ]\]</span></p>
<p>y se quiere probar <span class="math inline">\(H_0:b=0\)</span>. En este caso no se puede (ni se debe) usar las pruebas anteriores, sino a través del cálculo de:</p>
<p><span class="math display">\[s^2=\frac{1}{D-1}\sum_{i=1}^D\left[1-\sum_{j=1}^i\frac{1}{D-j+1}\right]\]</span></p>
<p>y el estadístico de prueba es:</p>
<p><span class="math display">\[Q=\frac{\max|S_k|}{s\sqrt{D-1}}\overset{H_0}{\underset{\text{n grande}}{\sim}}|\text{Puente Browniano}|\]</span></p>
<p>Note que si <span class="math inline">\(Q&gt;1\)</span>, entonces el valor p de la prueba anterior es aproximadamente <span class="math inline">\(2\exp[-2Q^2]\)</span>.</p>
</section>
<section id="estimación-de-la-función-de-sobrevivencia" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="estimación-de-la-función-de-sobrevivencia"><span class="header-section-number">4.5</span> Estimación de la función de sobrevivencia</h2>
<p><em>Objetivo</em>: Estimar la probabilidad de sobrevivencia de un nuevo individuo con covariables <span class="math inline">\(Z_0\)</span>.</p>
<p>Después de haber ajustado el modelo de Cox, sea <span class="math inline">\(b\)</span> el estimador de máxima verosimilitud parcial y <span class="math inline">\(\hat V(b)=I^{-1}(b)\)</span>. Bajo la notación usual, defina:</p>
<p><span class="math display">\[W(t_i,b)=\sum_{j \in R(t_i)}\exp\left(\sum_{h=1}^pb_hZ_{jh}\right)\]</span></p>
<p>y usando el estimador de Breslow, estimamos la tasa de riesgo acumulada base como:</p>
<p><span class="math display">\[\hat H_0(t)=\sum_{t_i\leq t}\frac{d_i}{W(t_i,b)}\]</span></p>
<p><em>Nota</em>: <span class="math inline">\(\hat H_0(t)\)</span> es el estimador de Nelson-Aalen cuando no hay covariables.</p>
<p>Usando el estimador anterior:</p>
<p><span class="math display">\[\hat S_0(t)=\exp[-\hat H_0(t)]\]</span></p>
<p>Para estimar la sobrevivencia de un individuo con vector de covariables <span class="math inline">\(Z=Z_0\)</span> usamos:</p>
<p><span class="math display">\[\hat S(t|Z=Z_0)=\hat S_0(t)^{\exp[b^TZ_0]}\]</span></p>
<p>Note que bajo ciertas condiciones:</p>
<p><span class="math display">\[\hat S(t|Z=Z_0)\overset{\text{t fijo}}{\underset{\text{n grande}}{\sim}} N(S(t|Z=Z_0), \hat V[\hat S(t|Z=Z_0)])\]</span></p>
<p>donde</p>
<p><span class="math display">\[\hat V[\hat S(t|Z=Z_0)]=[\hat S(t|Z=Z_0)]^2[Q_1(t)+Q_2(t;Z_0)]\]</span></p>
<p>y</p>
<p><span class="math display">\[Q_1(t)=\sum_{t_i\leq t}\frac{d_i}{W(t_i,b)^2}\]</span></p>
<p>el cual es el estimador de la varianza de <span class="math inline">\(\hat H_0(t)\)</span> si <span class="math inline">\(\beta=b\)</span>, además:</p>
<p><span class="math display">\[Q_2(t)=Q_3(t,Z_0)^T\hat V(b)Q_3(t,Z_0)\]</span></p>
<p>con <span class="math inline">\(Q_3\)</span> el vector de tamaño <span class="math inline">\(p\times 1\)</span> con <span class="math inline">\(k\)</span>-ésima entrada: (<span class="math inline">\(k=1,\ldots,p\)</span>)</p>
<p><span class="math display">\[Q_3(t,Z_0)_k=\sum_{t_i\leq t}\left[\frac{W^{(k)}(t_i,b)}{W(t_i,b)}-Z_{0k}\right]\left[\frac{d_i}{W(t_i,b)}\right]\]</span></p>
<p>donde</p>
<p><span class="math display">\[W^{(k)}(t_i,b)=\sum_{j \in R(t_i)}Z_{jk}\exp(b^TZ_j)\]</span></p>
<p>Usando <span class="math inline">\(\hat S(t|Z=Z_0)\)</span> y <span class="math inline">\(\hat V[\hat S(t|Z=Z_0)]\)</span> se puede construir intervalos de confianza para <span class="math inline">\(S(t|Z=Z_0)\)</span> usando las mismas técnicas que aprendimos en el caso no-paramétrico.</p>
<p><em>Nota</em>: Una alternativa para el estimador de Breslow, es el de Kalbfleish y Prentice, que en el caso de no-repeticiones sería:</p>
<p><span class="math display">\[\hat H_0(t)=\sum_{t_i\leq t}\left[1-\left(1-\frac{\delta_i\exp(b^TZ_i)}{W(t_i,b)}\right)^{\exp(-b^TZ_i)}\right]\]</span></p>
</section>
<section id="covariables-dependientes-del-tiempo" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="covariables-dependientes-del-tiempo"><span class="header-section-number">4.6</span> Covariables dependientes del tiempo</h2>
<p>Para incluir covariables dependientes del tiempo consideramos la siguiente estructura de datos:</p>
<p><span class="math display">\[[T_j,\delta_j,[Z_j(t), 0\leq t\leq T_j]]\]</span></p>
<p>para <span class="math inline">\(j=1,\ldots,n\)</span> donde:</p>
<ul>
<li><p><span class="math inline">\(T_j\)</span>: tiempo de ocurrencia de evento/censura</p></li>
<li><p><span class="math inline">\(\delta_j\)</span>: indicador de evento de riesgo y</p></li>
<li><p><span class="math inline">\(Z_j(t)=[Z_{j1(t)},\ldots,Z_{jp}(t)]\)</span>: covariables del <span class="math inline">\(j\)</span>-ésimo paciente en tiempo <span class="math inline">\(t\)</span>.</p></li>
</ul>
<p>Asumimos que <span class="math inline">\(Z_j(t)\)</span> es observable en el periodo de estudio y además que no hay repeticiones para distintos individuos en los tiempos de ocurrencia:</p>
<p><span class="math display">\[t_1&lt;t_2&lt;\cdots&lt;t_D\]</span></p>
<p>Sean <span class="math inline">\(Z_{(i)}(t)\)</span> las covariables asociadas al individuo con tiempo de ocurrencia <span class="math inline">\(t_i\)</span> y <span class="math inline">\(R(t_i)\)</span>: el grupo expuesto al riesgo al momento <span class="math inline">\(t_i\)</span>. En este caso la fórmula de verosimilitud parcial es:</p>
<p><span class="math display">\[L(\beta)=\prod_{i=1}^D\frac{\exp\left[\sum_{b=1}^p\beta_pZ_{(i)p}(t_i)\right]}{\sum_{j \in R(t_i)}\exp\left[\sum_{b=1}^p\beta_pZ_{jp}(t_i)\right]}\]</span></p>
<p>y los procesos de estimación puntual y pruebas de hipótesis son análogos. Si hay repeticiones en <span class="math inline">\(t_1&lt;\cdots&lt;t_D\)</span> entonces se puede generalizar <span class="math inline">\(L(\beta)\)</span> como en el caso de covariables estáticas.</p>
<section id="aplicación-prueba-de-riesgos-proporcionales" class="level3" data-number="4.6.1">
<h3 data-number="4.6.1" class="anchored" data-anchor-id="aplicación-prueba-de-riesgos-proporcionales"><span class="header-section-number">4.6.1</span> Aplicación: Prueba de Riesgos Proporcionales</h3>
<p>Sea <span class="math inline">\(Z_1\)</span> una covariable fija. Si se quiere probar la hipótesis de riesgos proporcionales para <span class="math inline">\(Z_1\)</span> entonces defina:</p>
<p><span class="math display">\[Z_2=Z_1\cdot g(t)\]</span></p>
<p>donde <span class="math inline">\(g(t)\)</span> es una función conocida. (usualmente <span class="math inline">\(g(t)=\log t\)</span>)</p>
<p>Considere un modelo de Cox con covariables <span class="math inline">\(Z_1\)</span> y <span class="math inline">\(Z_2\)</span>:</p>
<p><span class="math display">\[h(t|Z_1)=h_0(t)\exp[\beta_1Z_1+\beta_2(Z_1g(t))]\]</span></p>
<p>Compare dos individuos con covariables <span class="math inline">\(Z_1\)</span> y <span class="math inline">\(Z_1^*\)</span> a través de su riesgo relativo:</p>
<p><span class="math display">\[\frac{h(t|Z_1)}{h(t|Z_1^*)}=\exp[\beta_1(Z_1-Z_1^*)+\beta_2g(t)(Z_1-Z_1^*)]\]</span></p>
<p>Note que bajo la hipótesis <span class="math inline">\(H_0:\)</span> <em>riesgos proporcionales en</em> <span class="math inline">\(Z_1\)</span>, la parte derecha de la ecuación anterior no depende de <span class="math inline">\(t\)</span>. Por lo tanto <span class="math inline">\(H_0\)</span> es equivalente a la hipótesis <span class="math inline">\(H_0: \beta_2=0\)</span> la cual se puede verificar a través de la prueba de Wald, LRT o Score.</p>
<p>Si el supuesto de riesgos proporcionales no es cierto para <span class="math inline">\(Z_1\)</span> entonces se puede definir una covariable dependiente de tiempo:</p>
<span class="math display">\[\begin{align*}
Z_2(t)=
   \begin{cases}
     Z_1\cdot g(t) &amp; \text{si}\quad Z_1=1\\
     0 &amp; \text{si no}
   \end{cases}
\end{align*}\]</span>
<p>en el caso en que <span class="math inline">\(Z_1\)</span> fuera dicotómica. El principal problema a este momento es la estimación de la función <span class="math inline">\(g(t)\)</span>. Una posible solución es asumir que <span class="math inline">\(g(t)\)</span> es una variable indicadora. Definiríamos entonces:</p>
<span class="math display">\[\begin{align*}
Z_2(t)=
   \begin{cases}
     Z_1 &amp; t&gt;\tau \\
     0 &amp; t\leq \tau
   \end{cases}
\end{align*}\]</span>
<p>en este caso:</p>
<span class="math display">\[\begin{align*}
h(t|Z(t))=
   \begin{cases}
     h_0(t)\exp(\beta_1Z_1) &amp; t\leq \tau\\
     h_0(t)\exp((\beta_1+\beta_2)Z_1) &amp; t&gt;\tau
   \end{cases}
\end{align*}\]</span>
<p>y por lo tanto:</p>
<span class="math display">\[\begin{align*}
&amp;RR(Z_1=1\text{ vs } Z_1=0; t\leq \tau) = \exp(\beta_1)\\
&amp;RR(Z_1=1\text{ vs } Z_1=0; t&gt; \tau) = \exp(\beta_1+\beta_2)
\end{align*}\]</span>
<p>por este motivo a <span class="math inline">\(\tau\)</span> se le llama punto de cambio en el riesgo relativo. Otra codificación que se puede utilizar es a través del uso de un modelo con dos covariables: <span class="math inline">\(Z_2(t)\)</span> y</p>
<span class="math display">\[\begin{align*}
Z_3(t)=
   \begin{cases}
       Z_1 &amp; t\leq \tau\\
       0 &amp; t&gt;\tau
   \end{cases}
\end{align*}\]</span>
<p>Entonces:</p>
<span class="math display">\[\begin{align*}
h(t|Z(t))=
   \begin{cases}
     h_0(t)\exp(\theta_3 Z_1) &amp; t\leq \tau\\
     h_0(t)\exp(\theta_2 Z_1) &amp; t&gt;\tau
   \end{cases}
\end{align*}\]</span>
<p>y:</p>
<span class="math display">\[\begin{align*}
&amp;RR(Z_1=1\text{ vs } Z_1=0; t\leq \tau) = \exp(\theta_3)\\
&amp;RR(Z_1=1\text{ vs } Z_1=0; t&gt; \tau) = \exp(\theta_2)
\end{align*}\]</span>
<p>El siguiente paso es ajustar el modelo (bajo cualquiera de las dos codificaciones) para distintos valores de <span class="math inline">\(\tau\)</span> (tiempos de ocurrencia). El valor <span class="math inline">\(\tau\)</span> con máxima log-verosimilitud se toma como posible umbral.</p>
<p>Una prueba de riesgos proporcionales se hace en <span class="math inline">\(t\leq \tau\)</span> y <span class="math inline">\(t&gt;\tau\)</span>. Si en alguna de las dos regiones la prueba se rechaza, el proceso se repite.</p>
</section>
</section>
<section id="modelos-de-riesgos-proporcionales-estratificados" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="modelos-de-riesgos-proporcionales-estratificados"><span class="header-section-number">4.7</span> Modelos de riesgos proporcionales estratificados</h2>
<p>Otra solución en caso de que para una covariable el supuesto de riesgos proporcionales no sea cierto es a través del concepto de estratificación. Para el <span class="math inline">\(j\)</span>-ésimo estrato:</p>
<p><span class="math display">\[h_j(t|Z(t))=h_{0j}(t)\exp[\beta^TZ(t)]\qquad j=1,\ldots,s\]</span></p>
<p>se asume que el supuesto de riesgos proporcionales es cierto dentro de cada estrato y además el efecto de las covariables es el mismo sobre todos los estratos.</p>
<p>La log-verosimilitud parcial se puede escribir:</p>
<p><span class="math display">\[LL(\beta)=LL_1(\beta)+\cdots+LL_s(\beta)\]</span></p>
<p>donde <span class="math inline">\(LL_j(\beta)\)</span>: log-verosimilitud parcial usando la muestra del <span class="math inline">\(j\)</span>-ésimo estrato.</p>
<p>Para probar la hipótesis de que las covariables tienen el mismo efecto para cualquier estrato, se:</p>
<ul>
<li><p>Ajusta el modelo estratificado y se obtiene <span class="math inline">\(LL(b)\)</span>.</p></li>
<li><p>Para <span class="math inline">\(j=1,\ldots,s\)</span>, se ajusta el modelo con la muestra correspondiente al <span class="math inline">\(j\)</span>-ésimo estrato y se obtiene <span class="math inline">\(LL_j(b_j)\)</span></p></li>
</ul>
<p>Para probar <span class="math inline">\(H_0: \beta=\beta_j\)</span>, con <span class="math inline">\(j=1,\ldots,s\)</span> se usa un LRT con estadístico:</p>
<p><span class="math display">\[-2[LL(b)-\sum_{j=1}^sLL_j(b_j)]\overset{H_0}{\underset{\text{n grande}}{\sim}}\chi_{(s-1)p}^2\]</span></p>
<p><em>Nota:</em> también se puede verificar <span class="math inline">\(H_0\)</span> a través de la prueba de Wald. (ver libro de Klein).</p>
<p>Si la muestra está compuesta por pares de observaciones (muestra pareada) entonces se puede probar la igualdad de los <span class="math inline">\(\beta\)</span>’s entre grupos usando dos estratos y el LRT anterior (o prueba de Wald).</p>
</section>
<section id="truncamiento-por-la-izquierda" class="level2" data-number="4.8">
<h2 data-number="4.8" class="anchored" data-anchor-id="truncamiento-por-la-izquierda"><span class="header-section-number">4.8</span> Truncamiento por la izquierda</h2>
<p>En el caso de datos truncados se denota <span class="math inline">\(V_i\)</span>: tiempo de entrada al estudio del individuo <span class="math inline">\(i\)</span>-ésimo.</p>
<p>Para facilitar el cálculo, se supone que para cada individuo, el tiempo de evento <span class="math inline">\(X\)</span> y el tiempo de entrada <span class="math inline">\(V\)</span> son condicionalmente independientes dada la covariable <span class="math inline">\(Z\)</span>. Es decir:</p>
<p><span class="math display">\[P(X=t|Z,X&gt;V)=\frac{P(X=t,V&lt;t|Z)\cdot P(Z)}{P(Z,V&lt;X)}=\frac{P(X=t|Z)P(V&lt;t|Z)P(Z)}{P(Z,V&lt;X)}\]</span></p>
<p>De lo anterior se puede deducir:</p>
<p><span class="math display">\[h(t|Z,X&gt;V)=h(t|Z)\]</span></p>
<p>usando el hecho de que:</p>
<p><span class="math display">\[h(t|Z,X&gt;V)\approx \frac{P(X=t|Z,X&gt;V)}{P(X\geq t|Z,X&gt;V)}\]</span></p>
<p>Ajustando el conjunto de riesgo a:</p>
<p><span class="math display">\[R(t)=\{j|V_j&lt;t&lt;T_j\}\]</span></p>
<p>todos los métodos de inferencia vistos hasta ahora funcionan para ajustar el modelo de Cox.</p>
</section>
<section id="laboratorio" class="level2" data-number="4.9">
<h2 data-number="4.9" class="anchored" data-anchor-id="laboratorio"><span class="header-section-number">4.9</span> Laboratorio</h2>
<section id="primer-ejemplo-ejemplo-8.1" class="level3" data-number="4.9.1">
<h3 data-number="4.9.1" class="anchored" data-anchor-id="primer-ejemplo-ejemplo-8.1"><span class="header-section-number">4.9.1</span> Primer Ejemplo (Ejemplo 8.1)</h3>
<p>En este ejemplo tenemos una muestra de 45 mujeres a las que se le aplicó un procedimiento llamado “examinación inmunohistoquímica” con el fin de detectar cáncer. Los datos de sobrevivencia de las pacientes son:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survMisc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'survMisc'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:ggplot2':

    autoplot</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(KMsurv)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"btrial"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(btrial)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  time death im
1   19     1  1
2   25     1  1
3   30     1  1
4   34     1  1
5   37     1  1
6   46     1  1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(btrial)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      time            death              im     
 Min.   : 19.00   Min.   :0.0000   Min.   :1.0  
 1st Qu.: 51.00   1st Qu.:0.0000   1st Qu.:1.0  
 Median : 89.00   Median :1.0000   Median :1.0  
 Mean   : 98.33   Mean   :0.5333   Mean   :1.2  
 3rd Qu.:144.00   3rd Qu.:1.0000   3rd Qu.:1.0  
 Max.   :189.00   Max.   :1.0000   Max.   :2.0  </code></pre>
</div>
</div>
<p>en donde podemos notar que la variable <em>im</em> debería ser una variable categórica (factor) indicando presencia/ausencia del procedimiento. Esto lo corregimos transformando la variable y tomando como categoría base la ausencia del procedimiento:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>btrial <span class="ot">&lt;-</span> btrial <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">im=</span><span class="fu">factor</span>(im))</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(btrial<span class="sc">$</span>im)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  2
1 0
2 1</code></pre>
</div>
</div>
<p>Las funciones de sobrevivencia estimadas dependiendo del grupo “procedimiento” son:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survminer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: ggpubr</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'survminer'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:survival':

    myeloma</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>KM_8_1 <span class="ot">&lt;-</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(time,death)<span class="sc">~</span>im,<span class="at">data =</span> btrial)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsurvplot</span>(KM_8_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="RSP_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La diferencia evidente entre ambas funciones, sugiere que uno puede correr una regresión tomando la variable <em>im</em> como covariable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>modelo_8_1 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(time,death)<span class="sc">~</span>im,<span class="at">data =</span> btrial)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_8_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = Surv(time, death) ~ im, data = btrial)

  n= 45, number of events= 24 

      coef exp(coef) se(coef)     z Pr(&gt;|z|)  
im2 0.9802    2.6650   0.4349 2.254   0.0242 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

    exp(coef) exp(-coef) lower .95 upper .95
im2     2.665     0.3752     1.136      6.25

Concordance= 0.583  (se = 0.042 )
Likelihood ratio test= 4.45  on 1 df,   p=0.03
Wald test            = 5.08  on 1 df,   p=0.02
Score (logrank) test = 5.49  on 1 df,   p=0.02</code></pre>
</div>
</div>
<p>Note que el riesgo relativo de una paciente con un resultado positivo del procedimiento con respecto a una con un negativo es 2.67, es decir una paciente positiva es 2.67 más probable que fallezca con respecto a una que tuvo un resultado negativo. Un intervalo al 95% para el riesgo relativo de la población es [1.136,6.25].</p>
<p>También podemos probar la hipótesis de que el procedimiento no es significativo al 5%. Bajo cualquiera de las tres pruebas (LRT, Wald y Score) se rechaza esta hipótesis nula.</p>
</section>
<section id="segundo-ejemplo-ejemplo-8.2" class="level3" data-number="4.9.2">
<h3 data-number="4.9.2" class="anchored" data-anchor-id="segundo-ejemplo-ejemplo-8.2"><span class="header-section-number">4.9.2</span> Segundo ejemplo (Ejemplo 8.2)</h3>
<p>El segundo ejemplo tiene como base los datos de 90 hombres diagnosticados con cáncer de laringe con su edad de diagnóstico (age), tiempo de muerte o censura en meses (time), indicador de censura (delta) y etapa de la enfermedad (stage).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"larynx"</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(larynx)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     stage            time             age            diagyr     
 Min.   :1.000   Min.   : 0.100   Min.   :41.00   Min.   :70.00  
 1st Qu.:1.000   1st Qu.: 2.000   1st Qu.:57.00   1st Qu.:72.25  
 Median :2.000   Median : 4.000   Median :65.00   Median :74.00  
 Mean   :2.222   Mean   : 4.198   Mean   :64.61   Mean   :74.24  
 3rd Qu.:3.000   3rd Qu.: 6.200   3rd Qu.:72.00   3rd Qu.:76.00  
 Max.   :4.000   Max.   :10.700   Max.   :86.00   Max.   :78.00  
     delta       
 Min.   :0.0000  
 1st Qu.:0.0000  
 Median :1.0000  
 Mean   :0.5556  
 3rd Qu.:1.0000  
 Max.   :1.0000  </code></pre>
</div>
</div>
<p>Transformamos la variable <em>stage</em> para que sea factor, y mantenemos la variable discreta con el nombre <em>stage_n</em>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>larynx <span class="ot">&lt;-</span> larynx <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">stage_n =</span> stage) <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">stage=</span><span class="fu">factor</span>(stage))</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(larynx<span class="sc">$</span>stage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  2 3 4
1 0 0 0
2 1 0 0
3 0 1 0
4 0 0 1</code></pre>
</div>
</div>
<p>Noten que la base según esta codificación es la etapa 1 de la enfermedad. Corremos un modelo de Cox usando como covariable la etapa de la enfermedad, usando un estimador de Breslow en la tasa acumulada de riesgo base:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>modelo_8_2 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(time,delta)<span class="sc">~</span>stage,<span class="at">data=</span>larynx,<span class="at">ties =</span> <span class="st">'breslow'</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_8_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = Surv(time, delta) ~ stage, data = larynx, ties = "breslow")

  n= 90, number of events= 50 

          coef exp(coef) se(coef)     z Pr(&gt;|z|)    
stage2 0.06576   1.06797  0.45844 0.143   0.8859    
stage3 0.61206   1.84423  0.35520 1.723   0.0849 .  
stage4 1.72284   5.60040  0.41966 4.105 4.04e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

       exp(coef) exp(-coef) lower .95 upper .95
stage2     1.068     0.9364    0.4348     2.623
stage3     1.844     0.5422    0.9193     3.700
stage4     5.600     0.1786    2.4604    12.748

Concordance= 0.668  (se = 0.037 )
Likelihood ratio test= 16.26  on 3 df,   p=0.001
Wald test            = 18.95  on 3 df,   p=3e-04
Score (logrank) test = 22.46  on 3 df,   p=5e-05</code></pre>
</div>
</div>
<p>Por ejemplo el riesgo relativo de los pacientes con etapa 3 con respecto a etapa 1 es 1.844. El riesgo relativo de los pacientes etapa 3 con respecto a etapa 2 es:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fl">1.844</span><span class="sc">/</span><span class="fl">1.068</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.726592</code></pre>
</div>
</div>
<p>Además, la hipótesis nula de que el riesgo relativo es igual para las etapas de la enfermedad se rechaza facílmente bajo cualquiera de las tres pruebas de hipótesis (Wald, Score y LRT).</p>
<p>Como la prueba score en el modelo de Cox es la prueba logrank, al utilizar como covariable <em>stage_n</em> se estaría haciendo una prueba de tendencia:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>modelo_8_2_trend <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(time,delta)<span class="sc">~</span>stage_n,<span class="at">data=</span>larynx,<span class="at">ties =</span> <span class="st">'breslow'</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_8_2_trend)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = Surv(time, delta) ~ stage_n, data = larynx, ties = "breslow")

  n= 90, number of events= 50 

          coef exp(coef) se(coef)     z Pr(&gt;|z|)    
stage_n 0.5054    1.6577   0.1411 3.582  0.00034 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

        exp(coef) exp(-coef) lower .95 upper .95
stage_n     1.658     0.6032     1.257     2.186

Concordance= 0.668  (se = 0.037 )
Likelihood ratio test= 13.1  on 1 df,   p=3e-04
Wald test            = 12.83  on 1 df,   p=3e-04
Score (logrank) test = 13.64  on 1 df,   p=2e-04</code></pre>
</div>
</div>
<p>En este caso se rechaza la hipótesis de igualdad de funciones de sobrevivencia a favor de la hipótesis alternativa de decrecimiento en la sobrevivencia conforme se incrementa la etapa de la enfermedad.</p>
<p>Si introducimos como covariable la edad de diagnóstico:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>modelo_8_2_age <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo_8_2,<span class="at">formula. =</span> .<span class="sc">~</span>.<span class="sc">+</span>age)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_8_2_age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = Surv(time, delta) ~ stage + age, data = larynx, 
    ties = "breslow")

  n= 90, number of events= 50 

          coef exp(coef) se(coef)     z Pr(&gt;|z|)    
stage2 0.13856   1.14862  0.46231 0.300    0.764    
stage3 0.63835   1.89335  0.35608 1.793    0.073 .  
stage4 1.69306   5.43607  0.42221 4.010 6.07e-05 ***
age    0.01890   1.01908  0.01425 1.326    0.185    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

       exp(coef) exp(-coef) lower .95 upper .95
stage2     1.149     0.8706    0.4642     2.842
stage3     1.893     0.5282    0.9422     3.805
stage4     5.436     0.1840    2.3763    12.436
age        1.019     0.9813    0.9910     1.048

Concordance= 0.682  (se = 0.039 )
Likelihood ratio test= 18.07  on 4 df,   p=0.001
Wald test            = 20.82  on 4 df,   p=3e-04
Score (logrank) test = 24.33  on 4 df,   p=7e-05</code></pre>
</div>
</div>
<p>Por lo tanto el riesgo relativo de un paciente con edad de diagnóstico igual a 50 años con respecto a uno con 40 años cuando la etapa de la enfermedad es la misma es:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="dv">10</span><span class="sc">*</span>modelo_8_2_age<span class="sc">$</span>coefficients[<span class="dv">4</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     age 
1.208063 </code></pre>
</div>
</div>
<p>Es decir hay un incremento de un 21% aproximadamente en el riesgo de fallecer entre una persona con 50 años con respecto a una de 40 años si ambos están en la misma etapa de la enfermedad.</p>
<p>Si queremos probar la hipótesis nula de que <span class="math inline">\(H_0:\beta_1=\beta_2=\beta_3=0\)</span> en el modelo anterior podemos comparar a través de un LRT el modelo completo con todas las covariables y uno reducido con solamente la covariable edad:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>modelo_8_2_solo_age <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(time,delta)<span class="sc">~</span>age,<span class="at">data=</span>larynx,<span class="at">ties =</span> <span class="st">'breslow'</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo_8_2_age,modelo_8_2_solo_age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table
 Cox model: response is  Surv(time, delta)
 Model 1: ~ stage + age
 Model 2: ~ age
   loglik  Chisq Df Pr(&gt;|Chi|)   
1 -188.18                        
2 -195.91 15.453  3   0.001468 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Es decir rechazamos esta hipótesis bajo los niveles usuales de significancia. Si queremos comprobar la misma hipótesis con la prueba de Wald calculamos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>Ib_inv <span class="ot">&lt;-</span> modelo_8_2_age<span class="sc">$</span>var</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>X2w <span class="ot">&lt;-</span> <span class="fu">t</span>(modelo_8_2_age<span class="sc">$</span>coefficients[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>])<span class="sc">%*%</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">solve</span>(Ib_inv[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>])<span class="sc">%*%</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  modelo_8_2_age<span class="sc">$</span>coefficients[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(X2w,<span class="at">df =</span> <span class="dv">3</span>,<span class="at">lower.tail =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             [,1]
[1,] 0.0005245945</code></pre>
</div>
</div>
<p>y llegamos a la misma conclusión.</p>
<p>Las pruebas de Wald individuales en el modelo completo se obtienen directamente del mismo output:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_8_2_age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = Surv(time, delta) ~ stage + age, data = larynx, 
    ties = "breslow")

  n= 90, number of events= 50 

          coef exp(coef) se(coef)     z Pr(&gt;|z|)    
stage2 0.13856   1.14862  0.46231 0.300    0.764    
stage3 0.63835   1.89335  0.35608 1.793    0.073 .  
stage4 1.69306   5.43607  0.42221 4.010 6.07e-05 ***
age    0.01890   1.01908  0.01425 1.326    0.185    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

       exp(coef) exp(-coef) lower .95 upper .95
stage2     1.149     0.8706    0.4642     2.842
stage3     1.893     0.5282    0.9422     3.805
stage4     5.436     0.1840    2.3763    12.436
age        1.019     0.9813    0.9910     1.048

Concordance= 0.682  (se = 0.039 )
Likelihood ratio test= 18.07  on 4 df,   p=0.001
Wald test            = 20.82  on 4 df,   p=3e-04
Score (logrank) test = 24.33  on 4 df,   p=7e-05</code></pre>
</div>
</div>
<p>La hipótesis nula <span class="math inline">\(H_0:\beta_1=\beta_2=\beta_3\)</span> puede ser comprobada a través de una matriz de contrastes y usando el estadístico de prueba de la ecuación 8.5.7:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>betas <span class="ot">&lt;-</span> <span class="fu">coefficients</span>(modelo_8_2_age)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>Cmat <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>),<span class="at">nrow =</span> <span class="dv">2</span>,<span class="at">byrow =</span> T)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>X_C2 <span class="ot">&lt;-</span> <span class="fu">t</span>(Cmat<span class="sc">%*%</span>betas)<span class="sc">%*%</span><span class="fu">solve</span>(Cmat<span class="sc">%*%</span>Ib_inv<span class="sc">%*%</span><span class="fu">t</span>(Cmat))<span class="sc">%*%</span>Cmat<span class="sc">%*%</span>betas</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(X_C2,<span class="at">df =</span> <span class="dv">2</span>,<span class="at">lower.tail =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            [,1]
[1,] 0.004671744</code></pre>
</div>
</div>
<p>en donde rechazamos <span class="math inline">\(H_0\)</span> bajo los niveles de significancia usuales.</p>
<p>Si consideramos la interacción entre la edad de diagnóstico con la etapa de la enfermedad el modelo se puede estimar con:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>modelo_8_2_age_stage <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo_8_2_age,<span class="at">formula. =</span> .<span class="sc">~</span>.<span class="sc">+</span>stage<span class="sc">:</span>age)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_8_2_age_stage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = Surv(time, delta) ~ stage + age + stage:age, 
    data = larynx, ties = "breslow")

  n= 90, number of events= 50 

                coef exp(coef)  se(coef)      z Pr(&gt;|z|)  
stage2     -7.946142  0.000354  3.678209 -2.160   0.0307 *
stage3     -0.122500  0.884706  2.468331 -0.050   0.9604  
stage4      0.846986  2.332605  2.425717  0.349   0.7270  
age        -0.002559  0.997444  0.026051 -0.098   0.9218  
stage2:age  0.120254  1.127783  0.052307  2.299   0.0215 *
stage3:age  0.011351  1.011416  0.037449  0.303   0.7618  
stage4:age  0.013673  1.013767  0.035967  0.380   0.7038  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

           exp(coef) exp(-coef) lower .95 upper .95
stage2      0.000354  2824.6562 2.619e-07    0.4786
stage3      0.884705     1.1303 7.011e-03  111.6467
stage4      2.332605     0.4287 2.009e-02  270.7790
age         0.997444     1.0026 9.478e-01    1.0497
stage2:age  1.127783     0.8867 1.018e+00    1.2495
stage3:age  1.011416     0.9887 9.398e-01    1.0884
stage4:age  1.013767     0.9864 9.448e-01    1.0878

Concordance= 0.694  (se = 0.039 )
Likelihood ratio test= 24.27  on 7 df,   p=0.001
Wald test            = 24.11  on 7 df,   p=0.001
Score (logrank) test = 28.59  on 7 df,   p=2e-04</code></pre>
</div>
</div>
<p>y podemos usar una prueba LRT para verificar la significancia de la interacción:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo_8_2_age,modelo_8_2_age_stage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table
 Cox model: response is  Surv(time, delta)
 Model 1: ~ stage + age
 Model 2: ~ stage + age + stage:age
   loglik  Chisq Df Pr(&gt;|Chi|)
1 -188.18                     
2 -185.08 6.2039  3     0.1021</code></pre>
</div>
</div>
<p>que con un nivel de significancia del 5% (una muestra de 90 sujetos podría sugerir ese nivel) no se podría rechazar la hipótesis de no significancia de la interacción.</p>
<p>Finalmente vamos a estimar la función de sobrevivencia de un paciente con 60 años bajo los cuatro estados de la enfermedad. Recuerden que estamos usando la aproximación de Breslow:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>individuo <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">age=</span><span class="fu">rep</span>(<span class="dv">60</span>,<span class="dv">4</span>),<span class="at">stage=</span><span class="fu">factor</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>))</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>S_8_2_age <span class="ot">&lt;-</span> <span class="fu">survfit</span>(modelo_8_2_age,<span class="at">newdata =</span> individuo)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(S_8_2_age,<span class="at">col=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="RSP_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="tercer-ejemplo-ejemplo-8.3" class="level3" data-number="4.9.3">
<h3 data-number="4.9.3" class="anchored" data-anchor-id="tercer-ejemplo-ejemplo-8.3"><span class="header-section-number">4.9.3</span> Tercer ejemplo (Ejemplo 8.3)</h3>
<p>Este tercer ejemplo consiste en 863 pacientes de transplante de riñón con covariables etnia (race: <span class="math inline">\(R\)</span>) y sexo (gender: <span class="math inline">\(G\)</span>). Cargamos los datos y transformamos las dos covariables en variables tipo factor:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"kidtran"</span>)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(kidtran)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      obs             time          delta            gender     
 Min.   :  1.0   Min.   :   1   Min.   :0.0000   Min.   :1.000  
 1st Qu.:216.5   1st Qu.: 426   1st Qu.:0.0000   1st Qu.:1.000  
 Median :432.0   Median :1269   Median :0.0000   Median :1.000  
 Mean   :432.0   Mean   :1380   Mean   :0.1622   Mean   :1.393  
 3rd Qu.:647.5   3rd Qu.:2216   3rd Qu.:0.0000   3rd Qu.:2.000  
 Max.   :863.0   Max.   :3434   Max.   :1.0000   Max.   :2.000  
      race            age       
 Min.   :1.000   Min.   : 1.00  
 1st Qu.:1.000   1st Qu.:33.00  
 Median :1.000   Median :43.00  
 Mean   :1.175   Mean   :42.84  
 3rd Qu.:1.000   3rd Qu.:54.00  
 Max.   :2.000   Max.   :75.00  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>kidtran <span class="ot">&lt;-</span> kidtran <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">gender=</span><span class="fu">factor</span>(gender),<span class="at">race=</span><span class="fu">factor</span>(race))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Primero ajustamos un modelo en donde haya una interacción entre las dos covariables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>modelo_8_3 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(time,delta)<span class="sc">~</span>gender<span class="sc">*</span>race,<span class="at">data =</span> kidtran)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_8_3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = Surv(time, delta) ~ gender * race, data = kidtran)

  n= 863, number of events= 140 

                  coef exp(coef) se(coef)      z Pr(&gt;|z|)  
gender2       -0.24848   0.77998  0.19854 -1.252   0.2107  
race2         -0.08878   0.91504  0.29182 -0.304   0.7609  
gender2:race2  0.74549   2.10747  0.42711  1.745   0.0809 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

              exp(coef) exp(-coef) lower .95 upper .95
gender2           0.780     1.2821    0.5285     1.151
race2             0.915     1.0928    0.5165     1.621
gender2:race2     2.107     0.4745    0.9124     4.868

Concordance= 0.54  (se = 0.024 )
Likelihood ratio test= 4.37  on 3 df,   p=0.2
Wald test            = 4.64  on 3 df,   p=0.2
Score (logrank) test = 4.74  on 3 df,   p=0.2</code></pre>
</div>
</div>
<p>Note que en este caso los niveles base en ambas covariables son Masculino y etnia blanca. Hay que tener cuidado en este caso al calcular los riesgos relativos, por ejemplo el riesgo relativo de ser hombre negro con respecto a una mujer blanca es:</p>
<p><span class="math display">\[\frac{h(t|G=1,R=2)}{h(t|G=2,R=1)}=\frac{e^{-0.08878}}{e^{-0.24848}}=\frac{0.915}{0.78}=1.17\]</span></p>
<p>y el riesgo relativo de una mujer negra con respecto a una blanca:</p>
<p><span class="math display">\[\frac{h(t|G=2,R=2)}{h(t|G=2,R=1)}=\frac{e^{-0.8878-0.24848+0.74549}}{e^{-0.24848}}=0.915\cdot 2.107=1.928\]</span></p>
<p>Las pruebas de Wald, score y LRT no rechazan la hipótesis de no-significancia de la interacción y efectos principales del sexo y etnia sobre la sobrevivencia de la población en estudio.</p>
<p>Si ajustamos un modelo reducido con efectos principales solamente tenemos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>modelo_8_3_sInt <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo_8_3,<span class="at">formula. =</span> .<span class="sc">~</span>.<span class="sc">-</span>gender<span class="sc">:</span>race)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_8_3_sInt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = Surv(time, delta) ~ gender + race, data = kidtran)

  n= 863, number of events= 140 

            coef exp(coef) se(coef)      z Pr(&gt;|z|)
gender2 -0.09347   0.91077  0.17441 -0.536    0.592
race2    0.21992   1.24597  0.21148  1.040    0.298

        exp(coef) exp(-coef) lower .95 upper .95
gender2    0.9108     1.0980    0.6471     1.282
race2      1.2460     0.8026    0.8232     1.886

Concordance= 0.526  (se = 0.023 )
Likelihood ratio test= 1.35  on 2 df,   p=0.5
Wald test            = 1.39  on 2 df,   p=0.5
Score (logrank) test = 1.4  on 2 df,   p=0.5</code></pre>
</div>
</div>
<p>y podemos verificar a través de una prueba LRT si la interacción es significativa:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo_8_3_sInt,modelo_8_3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table
 Cox model: response is  Surv(time, delta)
 Model 1: ~ gender + race
 Model 2: ~ gender * race
   loglik  Chisq Df Pr(&gt;|Chi|)  
1 -878.50                       
2 -876.99 3.0222  1    0.08213 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Dado que la muestra es relativamente grande (863 individuos) uno pensaría que la significancia debería ser menor al menos al 5%. En este caso no podríamos rechazar la hipótesis de no-significancia de la interacción entre las dos covariables.</p>
<p>A pesar de esto el modelo reducido sigue siendo no significativo.</p>
<p>Un último ejercicio es la discretización de la covariable edad, ante distintas combinaciones de las dos covariables sexo y etnia. La discretización de la variable edad en dos grupos la podemos hacer a travéś de la prueba de Contal y O’Quigley, para los hombres de raza negra:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>muestraBM <span class="ot">&lt;-</span> kidtran <span class="sc">%&gt;%</span> <span class="fu">filter</span>(gender<span class="sc">==</span><span class="dv">1</span>,race<span class="sc">==</span><span class="dv">2</span>)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>model_c_BM <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(time,delta)<span class="sc">~</span>age,<span class="at">data =</span> muestraBM)</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_c_BM)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = Surv(time, delta) ~ age, data = muestraBM)

  n= 92, number of events= 14 

       coef exp(coef) se(coef)     z Pr(&gt;|z|)
age 0.03613   1.03679  0.02468 1.464    0.143

    exp(coef) exp(-coef) lower .95 upper .95
age     1.037     0.9645    0.9878     1.088

Concordance= 0.6  (se = 0.084 )
Likelihood ratio test= 2.43  on 1 df,   p=0.1
Wald test            = 2.14  on 1 df,   p=0.1
Score (logrank) test = 2.2  on 1 df,   p=0.1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>Contal_BM <span class="ot">&lt;-</span> <span class="fu">cutp</span>(model_c_BM)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>Contal_BM<span class="sc">$</span>age[<span class="dv">1</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   age        U        Q         p
1:  58 2.632404 0.802934 0.5393762</code></pre>
</div>
</div>
<p>en donde podemos observar que utilizar un umbral de 58 años permite obtener la mayor separabilidad entre los dos grupos a través del estadístico logrank. Usando la variable discreta y usando la variable continua no se rechaza la nula de no-significancia de la edad para este grupo.</p>
<p>El caso de hombres de raza blanca es:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>muestraWM <span class="ot">&lt;-</span> kidtran <span class="sc">%&gt;%</span> <span class="fu">filter</span>(gender<span class="sc">==</span><span class="dv">1</span>,race<span class="sc">==</span><span class="dv">1</span>)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>model_c_WM <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(time,delta)<span class="sc">~</span>age,<span class="at">data =</span> muestraWM)</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_c_WM)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = Surv(time, delta) ~ age, data = muestraWM)

  n= 432, number of events= 73 

       coef exp(coef) se(coef)     z Pr(&gt;|z|)    
age 0.06029   1.06214  0.01021 5.903 3.56e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

    exp(coef) exp(-coef) lower .95 upper .95
age     1.062     0.9415     1.041     1.084

Concordance= 0.695  (se = 0.027 )
Likelihood ratio test= 39.16  on 1 df,   p=4e-10
Wald test            = 34.85  on 1 df,   p=4e-09
Score (logrank) test = 36.66  on 1 df,   p=1e-09</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>Contal_WM <span class="ot">&lt;-</span> <span class="fu">cutp</span>(model_c_WM)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>Contal_WM<span class="sc">$</span>age[<span class="dv">1</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   age        U        Q            p
1:  41 25.21247 3.054644 1.571653e-08</code></pre>
</div>
</div>
<p>en donde de manera contraria la edad sí es significativa al explicar la sobrevivencia, a través de una edad umbral de 41 años.</p>
</section>
<section id="selección-de-variables" class="level3" data-number="4.9.4">
<h3 data-number="4.9.4" class="anchored" data-anchor-id="selección-de-variables"><span class="header-section-number">4.9.4</span> Selección de variables</h3>
<p>Los datos de este primer ejemplo corresponden a la base de sobrevivencia de 137 pacientes con transplante de médula ósea, los cuales se han dividido en tres grupos de riesgo dependiendo de su condición al momento del trasplante (ALL, AML-Low, AML-high). El riesgo a considerar es la muerte durante el tratamiento o reaparición de la leucemia. A continuación la carga de paquetes y datos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survMisc)</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(KMsurv)</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(bmt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Primero ajustamos un modelo de Cox en donde los grupos de riesgo son una covariable y comprobamos si la covariable aporta de forma significativa al explicar la sobrevivencia de la muestra:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>bmt <span class="ot">&lt;-</span> bmt <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">group=</span><span class="fu">factor</span>(group))</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>modelo1 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(<span class="at">time=</span>t2, <span class="at">event=</span>d3) <span class="sc">~</span> group, <span class="at">data=</span>bmt)</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = Surv(time = t2, event = d3) ~ group, data = bmt)

  n= 137, number of events= 83 

          coef exp(coef) se(coef)      z Pr(&gt;|z|)  
group2 -0.5742    0.5632   0.2873 -1.999   0.0457 *
group3  0.3834    1.4673   0.2674  1.434   0.1516  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

       exp(coef) exp(-coef) lower .95 upper .95
group2    0.5632     1.7757    0.3207     0.989
group3    1.4673     0.6815    0.8688     2.478

Concordance= 0.625  (se = 0.03 )
Likelihood ratio test= 13.45  on 2 df,   p=0.001
Wald test            = 13.03  on 2 df,   p=0.001
Score (logrank) test = 13.81  on 2 df,   p=0.001</code></pre>
</div>
</div>
<p>en donde notamos que para las tres pruebas LRT, Wald y Score se rechaza la hipótesis de que la variable categórica grupo no es significativa bajo niveles de significancia usuales. Hay otras variables que también se van a considerar como posibles predictores: tiempo de espera del transplante (waiting), clasificador FAB (FAB), indicador de MTX (MTX), Sexo de paciente (SXPa), Sexo de Donante (SXDo), CMV de paciente (CMVPa), CMV de donante (CMVDo), Edad de paciente (AgePa), Edad de donante (AgeDo)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>bmt <span class="ot">&lt;-</span> bmt <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">waiting=</span>z7,<span class="at">FAB=</span><span class="fu">factor</span>(z8),</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">MTX=</span><span class="fu">factor</span>(z10),<span class="at">SXPa=</span><span class="fu">factor</span>(z3),</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">SXDo=</span><span class="fu">factor</span>(z4),<span class="at">CMVPa=</span><span class="fu">factor</span>(z5),                      <span class="at">CMVDo=</span><span class="fu">factor</span>(z6),<span class="at">AgePa=</span>z1<span class="dv">-28</span>,<span class="at">AgeDo=</span>z2<span class="dv">-28</span>)</span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>bmt_2 <span class="ot">&lt;-</span> bmt <span class="sc">%&gt;%</span> <span class="fu">select</span>(t2,d3,group,waiting,FAB,MTX,SXPa,SXDo,</span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-9"><a href="#cb64-9" aria-hidden="true" tabindex="-1"></a>                       CMVPa,CMVDo,AgePa,AgeDo,ta,tc,tp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Definimos los modelos aumentados en una variable o factor a la vez y usamos la técnica de selección para adelante (Forward selection) como método de selección de variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>modelo1_1 <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo1,<span class="at">formula. =</span> .<span class="sc">~</span>.<span class="sc">+</span>waiting)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo1,modelo1_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table
 Cox model: response is  Surv(time = t2, event = d3)
 Model 1: ~ group
 Model 2: ~ group + waiting
   loglik  Chisq Df Pr(&gt;|Chi|)
1 -366.57                     
2 -365.90 1.3356  1     0.2478</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>modelo1_2 <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo1,<span class="at">formula. =</span> .<span class="sc">~</span>.<span class="sc">+</span>FAB)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo1,modelo1_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table
 Cox model: response is  Surv(time = t2, event = d3)
 Model 1: ~ group
 Model 2: ~ group + FAB
   loglik  Chisq Df Pr(&gt;|Chi|)   
1 -366.57                        
2 -362.42 8.2902  1   0.003986 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>modelo1_3 <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo1,<span class="at">formula. =</span> .<span class="sc">~</span>.<span class="sc">+</span>MTX)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo1,modelo1_3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table
 Cox model: response is  Surv(time = t2, event = d3)
 Model 1: ~ group
 Model 2: ~ group + MTX
   loglik Chisq Df Pr(&gt;|Chi|)
1 -366.57                    
2 -365.60  1.94  1     0.1637</code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>modelo1_4 <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo1,<span class="at">formula. =</span> .<span class="sc">~</span>.<span class="sc">+</span>SXPa<span class="sc">*</span>SXDo)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo1,modelo1_4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table
 Cox model: response is  Surv(time = t2, event = d3)
 Model 1: ~ group
 Model 2: ~ group + SXPa + SXDo + SXPa:SXDo
   loglik Chisq Df Pr(&gt;|Chi|)
1 -366.57                    
2 -365.65 1.847  3     0.6048</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>modelo1_5 <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo1,<span class="at">formula. =</span> .<span class="sc">~</span>.<span class="sc">+</span>CMVPa<span class="sc">*</span>CMVDo)</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo1,modelo1_5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table
 Cox model: response is  Surv(time = t2, event = d3)
 Model 1: ~ group
 Model 2: ~ group + CMVPa + CMVDo + CMVPa:CMVDo
   loglik  Chisq Df Pr(&gt;|Chi|)
1 -366.57                     
2 -366.48 0.1827  3     0.9803</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>modelo1_6 <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo1,<span class="at">formula. =</span> .<span class="sc">~</span>.<span class="sc">+</span>AgePa<span class="sc">*</span>AgeDo)</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo1,modelo1_6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table
 Cox model: response is  Surv(time = t2, event = d3)
 Model 1: ~ group
 Model 2: ~ group + AgePa + AgeDo + AgePa:AgeDo
   loglik  Chisq Df Pr(&gt;|Chi|)  
1 -366.57                       
2 -361.50 10.135  3    0.01745 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>La variable con mayor significancia es FAB, por lo tanto la agregamos al modelo reducido. Repetimos el proceso una vez más con el nuevo modelo completo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>modelo1_2_1 <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo1_2,<span class="at">formula. =</span> .<span class="sc">~</span>.<span class="sc">+</span>waiting)</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo1_2,modelo1_2_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table
 Cox model: response is  Surv(time = t2, event = d3)
 Model 1: ~ group + FAB
 Model 2: ~ group + FAB + waiting
   loglik  Chisq Df Pr(&gt;|Chi|)
1 -362.42                     
2 -361.76 1.3375  1     0.2475</code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>modelo1_2_2 <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo1_2,<span class="at">formula. =</span> .<span class="sc">~</span>.<span class="sc">+</span>MTX)</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo1_2,modelo1_2_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table
 Cox model: response is  Surv(time = t2, event = d3)
 Model 1: ~ group + FAB
 Model 2: ~ group + FAB + MTX
   loglik Chisq Df Pr(&gt;|Chi|)
1 -362.42                    
2 -361.45 1.958  1     0.1617</code></pre>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>modelo1_2_3 <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo1_2,<span class="at">formula. =</span> .<span class="sc">~</span>.<span class="sc">+</span>SXPa<span class="sc">*</span>SXDo)</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo1_2,modelo1_2_3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table
 Cox model: response is  Surv(time = t2, event = d3)
 Model 1: ~ group + FAB
 Model 2: ~ group + FAB + SXPa + SXDo + SXPa:SXDo
   loglik Chisq Df Pr(&gt;|Chi|)
1 -362.42                    
2 -361.97 0.901  3     0.8252</code></pre>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>modelo1_2_4 <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo1_2,<span class="at">formula. =</span> .<span class="sc">~</span>.<span class="sc">+</span>CMVPa<span class="sc">*</span>CMVDo)</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo1_2,modelo1_2_4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table
 Cox model: response is  Surv(time = t2, event = d3)
 Model 1: ~ group + FAB
 Model 2: ~ group + FAB + CMVPa + CMVDo + CMVPa:CMVDo
   loglik  Chisq Df Pr(&gt;|Chi|)
1 -362.42                     
2 -362.41 0.0208  3     0.9992</code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>modelo1_2_5 <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo1_2,<span class="at">formula. =</span> .<span class="sc">~</span>.<span class="sc">+</span>AgePa<span class="sc">*</span>AgeDo)</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo1_2,modelo1_2_5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table
 Cox model: response is  Surv(time = t2, event = d3)
 Model 1: ~ group + FAB
 Model 2: ~ group + FAB + AgePa + AgeDo + AgePa:AgeDo
   loglik  Chisq Df Pr(&gt;|Chi|)  
1 -362.42                       
2 -356.89 11.061  3     0.0114 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>La siguiente variable a incluir es la interacción de la edad del donante y paciente y sus efectos principales. Volvemos a hacer el análisis de nuevo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>modelo1_2_5_1 <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo1_2_5,<span class="at">formula. =</span> .<span class="sc">~</span>.<span class="sc">+</span>waiting)</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo1_2_5,modelo1_2_5_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table
 Cox model: response is  Surv(time = t2, event = d3)
 Model 1: ~ group + FAB + AgePa + AgeDo + AgePa:AgeDo
 Model 2: ~ group + FAB + AgePa + AgeDo + waiting + AgePa:AgeDo
   loglik Chisq Df Pr(&gt;|Chi|)
1 -356.89                    
2 -356.64 0.499  1     0.4799</code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>modelo1_2_5_2 <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo1_2_5,<span class="at">formula. =</span> .<span class="sc">~</span>.<span class="sc">+</span>MTX)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo1_2_5,modelo1_2_5_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table
 Cox model: response is  Surv(time = t2, event = d3)
 Model 1: ~ group + FAB + AgePa + AgeDo + AgePa:AgeDo
 Model 2: ~ group + FAB + AgePa + AgeDo + MTX + AgePa:AgeDo
   loglik  Chisq Df Pr(&gt;|Chi|)
1 -356.89                     
2 -356.20 1.3976  1     0.2371</code></pre>
</div>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>modelo1_2_5_3 <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo1_2_5,<span class="at">formula. =</span> .<span class="sc">~</span>.<span class="sc">+</span>SXPa<span class="sc">*</span>SXDo)</span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo1_2_5,modelo1_2_5_3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table
 Cox model: response is  Surv(time = t2, event = d3)
 Model 1: ~ group + FAB + AgePa + AgeDo + AgePa:AgeDo
 Model 2: ~ group + FAB + AgePa + AgeDo + SXPa + SXDo + AgePa:AgeDo + SXPa:SXDo
   loglik  Chisq Df Pr(&gt;|Chi|)
1 -356.89                     
2 -356.21 1.3677  3     0.7131</code></pre>
</div>
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>modelo1_2_5_4 <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo1_2_5,<span class="at">formula. =</span> .<span class="sc">~</span>.<span class="sc">+</span>CMVPa<span class="sc">*</span>CMVDo)</span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo1_2_5,modelo1_2_5_4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table
 Cox model: response is  Surv(time = t2, event = d3)
 Model 1: ~ group + FAB + AgePa + AgeDo + AgePa:AgeDo
 Model 2: ~ group + FAB + AgePa + AgeDo + CMVPa + CMVDo + AgePa:AgeDo + CMVPa:CMVDo
   loglik  Chisq Df Pr(&gt;|Chi|)
1 -356.89                     
2 -356.61 0.5644  3     0.9045</code></pre>
</div>
</div>
<p>y por lo tanto no agregamos variables adicionales. El modelo final tendría el siguiente resumen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo1_2_5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = Surv(time = t2, event = d3) ~ group + FAB + AgePa + 
    AgeDo + AgePa:AgeDo, data = bmt)

  n= 137, number of events= 83 

                  coef  exp(coef)   se(coef)      z Pr(&gt;|z|)    
group2      -1.0906476  0.3359988  0.3542790 -3.078 0.002080 ** 
group3      -0.4039052  0.6677074  0.3627767 -1.113 0.265549    
FAB1         0.8374156  2.3103883  0.2784644  3.007 0.002636 ** 
AgePa        0.0068204  1.0068437  0.0196830  0.347 0.728959    
AgeDo        0.0038723  1.0038798  0.0182562  0.212 0.832021    
AgePa:AgeDo  0.0031593  1.0031643  0.0009508  3.323 0.000891 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

            exp(coef) exp(-coef) lower .95 upper .95
group2         0.3360     2.9762    0.1678    0.6728
group3         0.6677     1.4977    0.3279    1.3595
FAB1           2.3104     0.4328    1.3386    3.9876
AgePa          1.0068     0.9932    0.9687    1.0464
AgeDo          1.0039     0.9961    0.9686    1.0405
AgePa:AgeDo    1.0032     0.9968    1.0013    1.0050

Concordance= 0.665  (se = 0.033 )
Likelihood ratio test= 32.8  on 6 df,   p=1e-05
Wald test            = 33.02  on 6 df,   p=1e-05
Score (logrank) test = 35.75  on 6 df,   p=3e-06</code></pre>
</div>
</div>
</section>
<section id="covariables-dependientes-del-tiempo-1" class="level3" data-number="4.9.5">
<h3 data-number="4.9.5" class="anchored" data-anchor-id="covariables-dependientes-del-tiempo-1"><span class="header-section-number">4.9.5</span> Covariables dependientes del tiempo</h3>
<p>Ahora vamos a considerar una variable dependiente del tiempo definida por:</p>
<span class="math display">\[\begin{align}
Z_A(t)=\begin{cases}
0 &amp; \text{si $t&lt;ta$}\\
1 &amp; \text{si no.}
\end{cases}
\end{align}\]</span>
<p>donde <em>ta</em> es el tiempo de ocurrencia de la enfermedad aguda de injerto contra huésped. Para incorporar esta covariable ajustamos la tabla de la siguiente forma:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>bmt_2 <span class="ot">&lt;-</span> bmt_2 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">id=</span><span class="dv">1</span><span class="sc">:</span><span class="fu">n</span>())</span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a>newbmt_2 <span class="ot">&lt;-</span> <span class="fu">tmerge</span>(<span class="at">data1 =</span> bmt_2,<span class="at">data2 =</span> bmt_2,<span class="at">id =</span> id,<span class="at">tstop =</span> t2)</span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-5"><a href="#cb97-5" aria-hidden="true" tabindex="-1"></a>newbmt_2 <span class="ot">&lt;-</span> <span class="fu">tmerge</span>(<span class="at">data1 =</span> newbmt_2,<span class="at">data2 =</span> bmt_2,<span class="at">id =</span> id,<span class="at">ZA=</span><span class="fu">tdc</span>(ta))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>También tenemos las siguientes dos variables que dependen del tiempo:</p>
<span class="math display">\[\begin{align}
Z_P(t)=\begin{cases}
0 &amp; \text{si $t&lt;tp$}\\
1 &amp; \text{si no.}
\end{cases}
\end{align}\]</span>
<p>y</p>
<span class="math display">\[\begin{align}
Z_C(t)=\begin{cases}
0 &amp; \text{si $t&lt;tc$}\\
1 &amp; \text{si no.}
\end{cases}
\end{align}\]</span>
<p>son las indicadoras de recuperación de plaquetas y de enfermedad crónica de injerto contra huésped respectivamente. Las incluimos en la base:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>newbmt_2 <span class="ot">&lt;-</span> <span class="fu">tmerge</span>(<span class="at">data1 =</span> newbmt_2,<span class="at">data2 =</span> bmt_2,<span class="at">id =</span> id,<span class="at">ZP=</span><span class="fu">tdc</span>(tp))</span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a>newbmt_2 <span class="ot">&lt;-</span> <span class="fu">tmerge</span>(<span class="at">data1 =</span> newbmt_2,<span class="at">data2 =</span> bmt_2,<span class="at">id =</span> id,<span class="at">ZC=</span><span class="fu">tdc</span>(tc),<span class="at">muerte=</span><span class="fu">event</span>(t2,d3))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>y la base queda así:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(newbmt_2,<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     t2 d3 group waiting FAB MTX SXPa SXDo CMVPa CMVDo AgePa AgeDo   ta  tc tp
1  2081  0     1      98   0   0    1    0     1     1    -2     5   67 121 13
2  2081  0     1      98   0   0    1    0     1     1    -2     5   67 121 13
3  2081  0     1      98   0   0    1    0     1     1    -2     5   67 121 13
4  2081  0     1      98   0   0    1    0     1     1    -2     5   67 121 13
5  1602  0     1    1720   0   0    1    1     0     0    -7     9 1602 139 18
6  1602  0     1    1720   0   0    1    1     0     0    -7     9 1602 139 18
7  1602  0     1    1720   0   0    1    1     0     0    -7     9 1602 139 18
8  1496  0     1     127   0   0    1    1     1     0    -2     7 1496 307 12
9  1496  0     1     127   0   0    1    1     1     0    -2     7 1496 307 12
10 1496  0     1     127   0   0    1    1     1     0    -2     7 1496 307 12
   id tstart tstop ZA ZP ZC muerte
1   1      0    13  0  0  0      0
2   1     13    67  0  1  0      0
3   1     67   121  1  1  0      0
4   1    121  2081  1  1  1      0
5   2      0    18  0  0  0      0
6   2     18   139  0  1  0      0
7   2    139  1602  0  1  1      0
8   3      0    12  0  0  0      0
9   3     12   307  0  1  0      0
10  3    307  1496  0  1  1      0</code></pre>
</div>
</div>
<p>Ajustamos un modelo que incluya la primer covariable <span class="math inline">\(Z_A(t)\)</span> sobre el modelo reducido que contiene solamente el grupo de riesgo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>modelo2 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(<span class="at">time =</span> tstart,<span class="at">time2 =</span> tstop,<span class="at">event =</span> muerte)<span class="sc">~</span>group<span class="sc">+</span>ZA,<span class="at">data =</span> newbmt_2)</span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a>modelo1 <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo2,<span class="at">formula. =</span> .<span class="sc">~</span>.<span class="sc">-</span>ZA)</span>
<span id="cb101-4"><a href="#cb101-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-5"><a href="#cb101-5" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo1,modelo2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table
 Cox model: response is  Surv(time = tstart, time2 = tstop, event = muerte)
 Model 1: ~ group
 Model 2: ~ group + ZA
   loglik  Chisq Df Pr(&gt;|Chi|)
1 -366.57                     
2 -365.97 1.2034  1     0.2726</code></pre>
</div>
</div>
<p>y hacemos lo mismo con modelos que incluyan de forma univariada las otras dos variables dependientes del tiempo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>modelo3 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(<span class="at">time =</span> tstart,<span class="at">time2 =</span> tstop,<span class="at">event =</span> muerte)<span class="sc">~</span>group<span class="sc">+</span>ZC,<span class="at">data =</span> newbmt_2)</span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo1,modelo3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table
 Cox model: response is  Surv(time = tstart, time2 = tstop, event = muerte)
 Model 1: ~ group
 Model 2: ~ group + ZC
   loglik  Chisq Df Pr(&gt;|Chi|)
1 -366.57                     
2 -366.36 0.4152  1     0.5193</code></pre>
</div>
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>modelo4 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(<span class="at">time =</span> tstart,<span class="at">time2 =</span> tstop,<span class="at">event =</span> muerte)<span class="sc">~</span>group<span class="sc">+</span>ZP,<span class="at">data =</span> newbmt_2)</span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo1,modelo4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table
 Cox model: response is  Surv(time = tstart, time2 = tstop, event = muerte)
 Model 1: ~ group
 Model 2: ~ group + ZP
   loglik Chisq Df Pr(&gt;|Chi|)   
1 -366.57                       
2 -361.86 9.421  1   0.002145 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>En donde se puede notar que la variable <span class="math inline">\(Z_P(t)\)</span> en significativa sobre un modelo reducido en donde solamente esté el grupo de riesgo de 3 niveles.</p>
<p>Ahora vamos a comparar el modelo completo que se obtuvo con selección para adelante con respecto al mismo modelo añadiendo la variable que depende del tiempo <span class="math inline">\(Z_P(t)\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a>modeloc1 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="at">formula =</span> <span class="fu">Surv</span>(<span class="at">time =</span> tstart,<span class="at">time2 =</span> tstop,<span class="at">event =</span> muerte) <span class="sc">~</span> group <span class="sc">+</span> FAB <span class="sc">+</span> AgePa<span class="sc">*</span>AgeDo, <span class="at">data =</span> newbmt_2)</span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-3"><a href="#cb107-3" aria-hidden="true" tabindex="-1"></a>modeloc2 <span class="ot">&lt;-</span> <span class="fu">update</span>(modeloc1,<span class="at">formula. =</span> .<span class="sc">~</span>.<span class="sc">+</span>ZP)</span>
<span id="cb107-4"><a href="#cb107-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-5"><a href="#cb107-5" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modeloc1,modeloc2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table
 Cox model: response is  Surv(time = tstart, time2 = tstop, event = muerte)
 Model 1: ~ group + FAB + AgePa * AgeDo
 Model 2: ~ group + FAB + AgePa + AgeDo + ZP + AgePa:AgeDo
   loglik  Chisq Df Pr(&gt;|Chi|)   
1 -356.89                        
2 -353.33 7.1311  1   0.007576 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Por lo tanto la variable <span class="math inline">\(Z_P(t)\)</span> sí es significativa sobre el modelo reducido con covariables fijas, ante los niveles usuales.</p>
<p>Ahora analizamos la inclusión de las interacciones de las covariables fijas con la variable <span class="math inline">\(Z_P(t)\)</span> usando selección forward:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a>modeloc2_1 <span class="ot">&lt;-</span> <span class="fu">update</span>(modeloc2,<span class="at">formula. =</span> .<span class="sc">~</span>.<span class="sc">+</span>ZP<span class="sc">:</span>group)</span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb109-3"><a href="#cb109-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modeloc2_1,modeloc2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table
 Cox model: response is  Surv(time = tstart, time2 = tstop, event = muerte)
 Model 1: ~ group + FAB + AgePa + AgeDo + ZP + AgePa:AgeDo + group:ZP
 Model 2: ~ group + FAB + AgePa + AgeDo + ZP + AgePa:AgeDo
   loglik  Chisq Df Pr(&gt;|Chi|)  
1 -349.89                       
2 -353.33 6.8765  2    0.03212 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a>modeloc2_2 <span class="ot">&lt;-</span> <span class="fu">update</span>(modeloc2,<span class="at">formula. =</span> .<span class="sc">~</span>.<span class="sc">+</span>ZP<span class="sc">:</span>FAB)</span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modeloc2_2,modeloc2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table
 Cox model: response is  Surv(time = tstart, time2 = tstop, event = muerte)
 Model 1: ~ group + FAB + AgePa + AgeDo + ZP + AgePa:AgeDo + FAB:ZP
 Model 2: ~ group + FAB + AgePa + AgeDo + ZP + AgePa:AgeDo
   loglik  Chisq Df Pr(&gt;|Chi|)  
1 -351.63                       
2 -353.33 3.4025  1     0.0651 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a>modeloc2_3 <span class="ot">&lt;-</span> <span class="fu">update</span>(modeloc2,<span class="at">formula. =</span> .<span class="sc">~</span>.<span class="sc">+</span>ZP<span class="sc">*</span>AgePa<span class="sc">*</span>AgeDo)</span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-3"><a href="#cb113-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modeloc2_3,modeloc2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table
 Cox model: response is  Surv(time = tstart, time2 = tstop, event = muerte)
 Model 1: ~ group + FAB + AgePa + AgeDo + ZP + AgePa:AgeDo + AgePa:ZP + AgeDo:ZP + AgePa:AgeDo:ZP
 Model 2: ~ group + FAB + AgePa + AgeDo + ZP + AgePa:AgeDo
   loglik  Chisq Df Pr(&gt;|Chi|)  
1 -349.44                       
2 -353.33 7.7836  3     0.0507 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>como el valor p más pequeño se obtiene al incluir la interacción ZP-group, entonces aumentamos el modelo de esa forma. Seguimos con el proceso:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a>modeloc2_1_1 <span class="ot">&lt;-</span> <span class="fu">update</span>(modeloc2_1,<span class="at">formula. =</span> .<span class="sc">~</span>.<span class="sc">+</span>ZP<span class="sc">:</span>FAB)</span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb115-3"><a href="#cb115-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modeloc2_1_1,modeloc2_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table
 Cox model: response is  Surv(time = tstart, time2 = tstop, event = muerte)
 Model 1: ~ group + FAB + AgePa + AgeDo + ZP + AgePa:AgeDo + group:ZP + FAB:ZP
 Model 2: ~ group + FAB + AgePa + AgeDo + ZP + AgePa:AgeDo + group:ZP
   loglik  Chisq Df Pr(&gt;|Chi|)  
1 -347.76                       
2 -349.89 4.2654  1     0.0389 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a>modeloc2_1_2 <span class="ot">&lt;-</span> <span class="fu">update</span>(modeloc2_1,<span class="at">formula. =</span> .<span class="sc">~</span>.<span class="sc">+</span>ZP<span class="sc">*</span>AgePa<span class="sc">*</span>AgeDo)</span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb117-3"><a href="#cb117-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modeloc2_1_2,modeloc2_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table
 Cox model: response is  Surv(time = tstart, time2 = tstop, event = muerte)
 Model 1: ~ group + FAB + AgePa + AgeDo + ZP + AgePa:AgeDo + group:ZP + AgePa:ZP + AgeDo:ZP + AgePa:AgeDo:ZP
 Model 2: ~ group + FAB + AgePa + AgeDo + ZP + AgePa:AgeDo + group:ZP
   loglik  Chisq Df Pr(&gt;|Chi|)   
1 -343.81                        
2 -349.89 12.157  3   0.006863 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Agregamos la interacción ZP-Edad, y finalmente vemos si la última interacción es signficativa sobre este modelo completo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a>modeloc2_1_2_1 <span class="ot">&lt;-</span> <span class="fu">update</span>(modeloc2_1_2,<span class="at">formula. =</span> .<span class="sc">~</span>.<span class="sc">+</span>ZP<span class="sc">:</span>FAB)</span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-3"><a href="#cb119-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modeloc2_1_2_1,modeloc2_1_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table
 Cox model: response is  Surv(time = tstart, time2 = tstop, event = muerte)
 Model 1: ~ group + FAB + AgePa + AgeDo + ZP + AgePa:AgeDo + group:ZP + AgePa:ZP + AgeDo:ZP + FAB:ZP + AgePa:AgeDo:ZP
 Model 2: ~ group + FAB + AgePa + AgeDo + ZP + AgePa:AgeDo + group:ZP + AgePa:ZP + AgeDo:ZP + AgePa:AgeDo:ZP
   loglik  Chisq Df Pr(&gt;|Chi|)  
1 -341.50                       
2 -343.81 4.6133  1    0.03172 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>y también lo incluimos asumiendo un nivel de significancia del 5%. El modelo final queda:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modeloc2_1_2_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = Surv(time = tstart, time2 = tstop, event = muerte) ~ 
    group + FAB + AgePa + AgeDo + ZP + AgePa:AgeDo + group:ZP + 
        AgePa:ZP + AgeDo:ZP + FAB:ZP + AgePa:AgeDo:ZP, data = newbmt_2)

  n= 341, number of events= 83 

                     coef  exp(coef)   se(coef)      z Pr(&gt;|z|)    
group2          1.3259769  3.7658623  0.8195521  1.618 0.105678    
group3          1.1345132  3.1096595  1.2249850  0.926 0.354371    
FAB1           -1.2506736  0.2863119  1.1125887 -1.124 0.260966    
AgePa          -0.1537743  0.8574656  0.0545406 -2.819 0.004811 ** 
AgeDo           0.1163506  1.1233897  0.0434345  2.679 0.007389 ** 
ZP             -0.2868383  0.7506331  0.6954226 -0.412 0.679998    
AgePa:AgeDo     0.0025965  1.0025998  0.0019434  1.336 0.181543    
group2:ZP      -3.0569781  0.0470296  0.9265028 -3.299 0.000969 ***
group3:ZP      -1.8945809  0.1503814  1.2914215 -1.467 0.142362    
AgePa:ZP        0.1932964  1.2132423  0.0587831  3.288 0.001008 ** 
AgeDo:ZP       -0.1467497  0.8635101  0.0480649 -3.053 0.002264 ** 
FAB1:ZP         2.4709992 11.8342655  1.1594144  2.131 0.033069 *  
AgePa:AgeDo:ZP  0.0001393  1.0001393  0.0022979  0.061 0.951673    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

               exp(coef) exp(-coef) lower .95 upper .95
group2           3.76586     0.2655  0.755545   18.7702
group3           3.10966     0.3216  0.281841   34.3101
FAB1             0.28631     3.4927  0.032345    2.5344
AgePa            0.85747     1.1662  0.770534    0.9542
AgeDo            1.12339     0.8902  1.031713    1.2232
ZP               0.75063     1.3322  0.192080    2.9334
AgePa:AgeDo      1.00260     0.9974  0.998788    1.0064
group2:ZP        0.04703    21.2632  0.007651    0.2891
group3:ZP        0.15038     6.6498  0.011966    1.8900
AgePa:ZP         1.21324     0.8242  1.081213    1.3614
AgeDo:ZP         0.86351     1.1581  0.785877    0.9488
FAB1:ZP         11.83427     0.0845  1.219680  114.8250
AgePa:AgeDo:ZP   1.00014     0.9999  0.995645    1.0047

Concordance= 0.735  (se = 0.027 )
Likelihood ratio test= 63.58  on 13 df,   p=1e-08
Wald test            = 60.54  on 13 df,   p=4e-08
Score (logrank) test = 74.92  on 13 df,   p=1e-10</code></pre>
</div>
</div>
</section>
<section id="prueba-alternativa-de-riesgos-proporcionales" class="level3" data-number="4.9.6">
<h3 data-number="4.9.6" class="anchored" data-anchor-id="prueba-alternativa-de-riesgos-proporcionales"><span class="header-section-number">4.9.6</span> Prueba alternativa de riesgos proporcionales:</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a>modelou1 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(<span class="at">time=</span>t2, <span class="at">event=</span>d3) <span class="sc">~</span> group<span class="sc">+</span>waiting<span class="sc">+</span>FAB<span class="sc">+</span>MTX<span class="sc">+</span>CMVPa<span class="sc">+</span>CMVDo<span class="sc">+</span>AgePa<span class="sc">+</span>AgeDo, <span class="at">data=</span>bmt_2)</span>
<span id="cb123-2"><a href="#cb123-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-3"><a href="#cb123-3" aria-hidden="true" tabindex="-1"></a>resu1 <span class="ot">&lt;-</span> <span class="fu">cox.zph</span>(modelou1)</span>
<span id="cb123-4"><a href="#cb123-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-5"><a href="#cb123-5" aria-hidden="true" tabindex="-1"></a>resu1<span class="sc">$</span>table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             chisq df           p
group    2.3343408  2 0.311246401
waiting  0.2570982  1 0.612120763
FAB      0.3166363  1 0.573636142
MTX      8.2423697  1 0.004092367
CMVPa    0.2360214  1 0.627094548
CMVDo    0.6284502  1 0.427924365
AgePa    0.6954160  1 0.404328284
AgeDo    3.5213560  1 0.060582862
GLOBAL  18.0494765  9 0.034603845</code></pre>
</div>
</div>
<p>Esta prueba se basa en los residuos estandarizados de Schoenfeld y no en la prueba que aparece en el Klein. En unas semanas estaremos profundizando en este tema de residuos. La implementación de la prueba de riesgos proporcionales se ilustra para dos variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a>modelou2_1 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(<span class="at">time=</span>t2, <span class="at">event=</span>d3) <span class="sc">~</span> waiting<span class="sc">+</span><span class="fu">tt</span>(waiting), <span class="at">data=</span>bmt_2,<span class="at">tt=</span><span class="cf">function</span>(x,t, ...) x<span class="sc">*</span><span class="fu">log</span>(t))</span>
<span id="cb125-2"><a href="#cb125-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb125-3"><a href="#cb125-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelou2_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = Surv(time = t2, event = d3) ~ waiting + tt(waiting), 
    data = bmt_2, tt = function(x, t, ...) x * log(t))

  n= 137, number of events= 83 

                  coef  exp(coef)   se(coef)      z Pr(&gt;|z|)
waiting      7.484e-06  1.000e+00  1.297e-03  0.006    0.995
tt(waiting) -1.759e-05  1.000e+00  2.480e-04 -0.071    0.943

            exp(coef) exp(-coef) lower .95 upper .95
waiting             1          1    0.9975     1.003
tt(waiting)         1          1    0.9995     1.000

Concordance= 0.453  (se = 0.031 )
Likelihood ratio test= 0.08  on 2 df,   p=1
Wald test            = 0.07  on 2 df,   p=1
Score (logrank) test = 0.07  on 2 df,   p=1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a>bmt_3 <span class="ot">&lt;-</span> bmt <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">MTX2=</span><span class="fu">as.numeric</span>(MTX)<span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb127-2"><a href="#cb127-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-3"><a href="#cb127-3" aria-hidden="true" tabindex="-1"></a>modelou2_2 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(<span class="at">time=</span>t2, <span class="at">event=</span>d3) <span class="sc">~</span> MTX2<span class="sc">+</span><span class="fu">tt</span>(MTX2), <span class="at">data=</span>bmt_3,<span class="at">tt=</span><span class="cf">function</span>(x,t, ...) x<span class="sc">*</span><span class="fu">log</span>(t))</span>
<span id="cb127-4"><a href="#cb127-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-5"><a href="#cb127-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelou2_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = Surv(time = t2, event = d3) ~ MTX2 + tt(MTX2), 
    data = bmt_3, tt = function(x, t, ...) x * log(t))

  n= 137, number of events= 83 

            coef exp(coef) se(coef)      z Pr(&gt;|z|)  
MTX2      2.6926   14.7706   1.1258  2.392   0.0168 *
tt(MTX2) -0.4616    0.6303   0.2219 -2.080   0.0376 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

         exp(coef) exp(-coef) lower .95 upper .95
MTX2       14.7706     0.0677     1.626  134.1903
tt(MTX2)    0.6303     1.5865     0.408    0.9738

Concordance= 0.58  (se = 0.027 )
Likelihood ratio test= 7.78  on 2 df,   p=0.02
Wald test            = 7.02  on 2 df,   p=0.03
Score (logrank) test = 8.6  on 2 df,   p=0.01</code></pre>
</div>
</div>
<p>A partir de los cálculos anteriores y la tabla 9.5 concluimos que la variable que tiene más evidencia de no seguir la hipótesis de riesgos proporcionales es MTX.</p>
<p>Una posible forma de solucionar la dependencia temporal del riesgo relativo de MTX es a través de la estratificación del modelo anterior de Cox:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a>modeloc2_est <span class="ot">&lt;-</span> <span class="fu">update</span>(modeloc2,<span class="at">formula. =</span> .<span class="sc">~</span>.<span class="sc">+</span><span class="fu">strata</span>(MTX))</span>
<span id="cb129-2"><a href="#cb129-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-3"><a href="#cb129-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modeloc2_est)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = Surv(time = tstart, time2 = tstop, event = muerte) ~ 
    group + FAB + AgePa + AgeDo + ZP + strata(MTX) + AgePa:AgeDo, 
    data = newbmt_2)

  n= 341, number of events= 83 

                  coef  exp(coef)   se(coef)      z Pr(&gt;|z|)   
group2      -0.9904320  0.3714162  0.3664891 -2.702  0.00688 **
group3      -0.3602323  0.6975143  0.3712785 -0.970  0.33192   
FAB1         0.8918863  2.4397273  0.2833168  3.148  0.00164 **
AgePa        0.0093842  1.0094283  0.0198368  0.473  0.63616   
AgeDo       -0.0015376  0.9984636  0.0179129 -0.086  0.93160   
ZP          -0.9951417  0.3696711  0.3458298 -2.878  0.00401 **
AgePa:AgeDo  0.0025651  1.0025684  0.0009374  2.736  0.00621 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

            exp(coef) exp(-coef) lower .95 upper .95
group2         0.3714     2.6924    0.1811    0.7618
group3         0.6975     1.4337    0.3369    1.4441
FAB1           2.4397     0.4099    1.4002    4.2511
AgePa          1.0094     0.9907    0.9709    1.0494
AgeDo          0.9985     1.0015    0.9640    1.0341
ZP             0.3697     2.7051    0.1877    0.7281
AgePa:AgeDo    1.0026     0.9974    1.0007    1.0044

Concordance= 0.712  (se = 0.029 )
Likelihood ratio test= 38.2  on 7 df,   p=3e-06
Wald test            = 40.28  on 7 df,   p=1e-06
Score (logrank) test = 44.49  on 7 df,   p=2e-07</code></pre>
</div>
</div>
<p>este resultado se puede comparar con la tabla 9.7. Como ejercicio les recomiendo completar la tabla 9.8 a través de la comparación de los coeficientes de los dos modelos con datos restringidos sobre MTX:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a>modeloc2_est_1 <span class="ot">&lt;-</span> <span class="fu">update</span>(modeloc2,<span class="at">data=</span><span class="fu">subset</span>(newbmt_2,<span class="at">subset =</span> MTX<span class="sc">==</span><span class="dv">1</span>))</span>
<span id="cb131-2"><a href="#cb131-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb131-3"><a href="#cb131-3" aria-hidden="true" tabindex="-1"></a><span class="fu">coefficients</span>(modeloc2_est_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      group2       group3         FAB1        AgePa        AgeDo           ZP 
-0.563717043 -0.858281947  0.344075277  0.011525761  0.034240833 -1.006880993 
 AgePa:AgeDo 
 0.001384428 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a>modeloc2_est_2 <span class="ot">&lt;-</span> <span class="fu">update</span>(modeloc2,<span class="at">data=</span><span class="fu">subset</span>(newbmt_2,<span class="at">subset =</span> MTX<span class="sc">==</span><span class="dv">0</span>))</span>
<span id="cb133-2"><a href="#cb133-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb133-3"><a href="#cb133-3" aria-hidden="true" tabindex="-1"></a><span class="fu">coefficients</span>(modeloc2_est_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      group2       group3         FAB1        AgePa        AgeDo           ZP 
-1.196548537 -0.290254448  1.088960082  0.027276837 -0.020204863 -0.867470829 
 AgePa:AgeDo 
 0.002270538 </code></pre>
</div>
</div>
</section>
<section id="datos-truncados-por-la-izquierda" class="level3" data-number="4.9.7">
<h3 data-number="4.9.7" class="anchored" data-anchor-id="datos-truncados-por-la-izquierda"><span class="header-section-number">4.9.7</span> Datos truncados por la izquierda</h3>
<p>Como último cálculo se hará el ajuste del modelo estratificado con MTX pero considerando solamente pacientes que cuyas plaquetas hayan retornado a un nivel normal (variable <span class="math inline">\(Z_P(t)\)</span>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a>newbmt_2_ZP <span class="ot">&lt;-</span> newbmt_2 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ZP<span class="sc">==</span><span class="dv">1</span>)</span>
<span id="cb135-2"><a href="#cb135-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb135-3"><a href="#cb135-3" aria-hidden="true" tabindex="-1"></a>modeloc2_est_trunc <span class="ot">&lt;-</span> <span class="fu">update</span>(modeloc2_est,<span class="at">formula. =</span> .<span class="sc">~</span>.<span class="sc">-</span>ZP,<span class="at">data=</span>newbmt_2_ZP)</span>
<span id="cb135-4"><a href="#cb135-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb135-5"><a href="#cb135-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modeloc2_est_trunc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = Surv(time = tstart, time2 = tstop, event = muerte) ~ 
    group + FAB + AgePa + AgeDo + strata(MTX) + AgePa:AgeDo, 
    data = newbmt_2_ZP)

  n= 195, number of events= 67 

                 coef exp(coef)  se(coef)      z Pr(&gt;|z|)    
group2      -1.752137  0.173403  0.437522 -4.005 6.21e-05 ***
group3      -0.747627  0.473489  0.407626 -1.834   0.0666 .  
FAB1         1.278075  3.589722  0.324847  3.934 8.34e-05 ***
AgePa        0.041660  1.042540  0.022294  1.869   0.0617 .  
AgeDo       -0.034750  0.965846  0.020675 -1.681   0.0928 .  
AgePa:AgeDo  0.002300  1.002302  0.001224  1.878   0.0603 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

            exp(coef) exp(-coef) lower .95 upper .95
group2         0.1734     5.7669   0.07356    0.4088
group3         0.4735     2.1120   0.21298    1.0526
FAB1           3.5897     0.2786   1.89911    6.7853
AgePa          1.0425     0.9592   0.99797    1.0891
AgeDo          0.9658     1.0354   0.92749    1.0058
AgePa:AgeDo    1.0023     0.9977   0.99990    1.0047

Concordance= 0.72  (se = 0.033 )
Likelihood ratio test= 37.3  on 6 df,   p=2e-06
Wald test            = 32.27  on 6 df,   p=1e-05
Score (logrank) test = 36.19  on 6 df,   p=3e-06</code></pre>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./PH.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Pruebas de Hipótesis</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./DRSP.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Análisis de Diagnósticos en el Modelo de Cox</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>